### ISSUE TITLE
Selection of items not working correctly after saving entity

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#109]
### What is the current behaviour?

In general the selection using item picker works as expected. However we have noticed a strange behaviour when creating a new node, clicking save & publish and then using the item picker. When selecting e.g. 3 items after the Umbraco content/entity has been created and clicking submit if only shows 1 single item and after clicking save & publish again no items are saved.

It also doesn't seem to be an issue with the selection directly when creating a new content node and using the item picker before the node is saved.

### What is the expected behaviour?
The selection of the item picker should work in same way after creating the entity as on existing nodes/entities.

### Please tell us about your set-up:

- Contentment version: [1.4.2]
- Umbraco version: [8.13.0]
- Umbraco ModelsBuilder  is: [enabled]
- Browser: [all]

In this scenario I get a console error:

![image](https://user-images.githubusercontent.com/2919859/118497427-5acd2980-b725-11eb-8db1-57ede3e0205b.png)

### Test notes

- Create a new content node by filling name and click "Save & Publish"
- Select a few items in the Contentment property using Item Picker and click submit.
- It should show a console error as in the screenshot above and not show all selected items.

I guess it is an issue somewhere where it is trying to push an item to `$scope.model.value`, but where this is null, undefined or maybe just an empty string.

**Comment by bjarnef** [comment]
It seems to be related to this:

![image](https://user-images.githubusercontent.com/2919859/118614035-9f0d0800-b7bf-11eb-8a3f-69b2b1d39822.png)

**Comment by leekelleher** [comment]
@bjarnef Just to let you know that I can reproduce the issue.
Quite odd that the page save sets the value as an empty string. I'm looking into resolutions. 👍

**Comment by leekelleher** [comment]
@bjarnef I've put a fix in commit 9b209212a2baa3e7e063bd2a54b78e41c603b434, but that's currently in the v2.0 branch, _(as that's where my current focus is at),_ but if I get time next week, then I'll look as doing a v1.4.3 patch release with other recent fixes.

**Comment by bjarnef** [comment]
@leekelleher okay, maybe a datatype storing JSON by default return an empty string, when the entity is created?
Anyway would be great to backport to v1.4.3 as well 🤓👍
