### ISSUE TITLE
Umbraco v9 upgrade fails with Contentment v3 alpha installed

### ISSUE THREAD

**Issue by JasonElkin** [leekelleher/umbraco-contentment#130]
### Which Contentment version are you using?

3.0.0-alpha003

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

9.0.0-rc001/9.0.0-rc002

### Bug summary

Haven't had a chance to test if properly can reproduce so please forgive me if this is a little trigger happy.

Had contentment installed on 9.0.0-rc001. After installing 9.0.0-rc002 I got the error below and Umbraco would return a 503 on the "AuthorizeUpgrade" page.

[21:24:25 ERR] A suitable constructor for type 'Umbraco.Community.Contentment.Composing.ContentmentListItemCollection' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

### Steps to reproduce

Install Umbraco 9.0.0-rc001
Install Contentment
Install Umbraco 9.0.0-rc002 
Run

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by JasonElkin** [comment]
Ah, looks like this is already fixed by #127

**Comment by leekelleher** [comment]
Yes, that's correct. I haven't had chance to get a new release out since Umbraco v9.0.0-rc002 came out. Heavy workload and kids summer holiday have zapped my free time. Hopefully I'll get a release out soon. 😊

**Comment by leekelleher** [comment]
[Contentment v3.0.0-alpha004](https://github.com/leekelleher/umbraco-contentment/releases/tag/3.0.0-alpha004) is now out!
