### ISSUE TITLE
Datalist value chosen from the drop down always result variable to be null 

### ISSUE THREAD

**Issue by OmarZidan1997** [leekelleher/umbraco-contentment#134]
### Which Contentment version are you using?

2.1.0

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

8.13.0

### Bug summary

Hi!

I have a problem to get the value of the dropdown list from the model as the variable always is null even though i have selected a value from the list that I have created. Following this guide https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/editors/data-list.md . 

this is the code i have in my datasource:

```csharp
public class AuthorMemberDataSource : IDataListSource, IDataListSourceValueConverter
{
    public string Name => "Authors";

    public string Description => "Data source for all the authors in members list.";

    public string Icon => "icon-addressbook";

    public OverlaySize OverlaySize => OverlaySize.Small;

    public Dictionary<string, object> DefaultValues => new Dictionary<string, object>();

    public IEnumerable<ConfigurationField> Fields => Enumerable.Empty<ConfigurationField>();

    IEnumerable<ConfigurationField> IContentmentEditorItem.Fields => Enumerable.Empty<ConfigurationField>();

    string IContentmentEditorItem.Group => string.Empty;

    public IEnumerable<DataListItem> GetItems(Dictionary<string, object> config)
    {
        var items = new List<DataListItem>();

        foreach (var timezone in TimeZoneInfo.GetSystemTimeZones())
        {
            items.Add(new DataListItem
            {
                Name = timezone.DisplayName,
                Value = timezone.Id
            });
        }

        return items;
    }

    public Type GetValueType(Dictionary<string, object> config)
    {
        return typeof(TimeZoneInfo);
    }

    public object ConvertValue(Type type, string value)
    {
        return TimeZoneInfo.FindSystemTimeZoneById(value);
    }
}
```

### Steps to reproduce

Just select any data source, create the data type out of that. Then go to content and select any value from the list. In my example its what im showing below in the image : 

![Screenshot_4](https://user-images.githubusercontent.com/54768891/134811421-b706f9a8-dd14-4c07-9014-a01697b424c4.png)
 I have a value selected which is (UTC-09:30) Marquesas Isla...

When i check my model values and look for "shareBlockAuthor" property, it shows that the property is null.. It should be a string containing the dropdown option value i selected.. Check image for demonstration : 

![image](https://user-images.githubusercontent.com/54768891/134812168-605d83ad-fc5d-40a4-9035-095a49e01ab1.png)

### Do you have Umbraco ModelsBuilder enabled?

- [x] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome

**Comment by leekelleher** [comment]
@OmarZidan1997 Thanks for raising this.

Strange that the value is `null`. I'm wondering if the `ConvertValue` method is being hit. Would you be able to set a breakpoint on that method and see if it hits?

**Comment by OmarZidan1997** [comment]
> @OmarZidan1997 Thanks for raising this.
> 
> Strange that the value is `null`. I'm wondering if the `ConvertValue` method is being hit. Would you be able to set a breakpoint on that method and see if it hits?

Problem is solved.. I dont know how it it solved but it just did.. It must've been something with cache things or a hidden ghost in my project... Thank you for time and your amazing nuget package! We love it!.

**Comment by leekelleher** [comment]
@OmarZidan1997 Cool, I'm glad the issue has resolved itself. 👍
