### ISSUE TITLE
[v9] Contentment crashes Umbraco during initial install

### ISSUE THREAD

**Issue by arknu** [leekelleher/umbraco-contentment#135]
### Which Contentment version are you using?

3.0.0-alpha005

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

9.0.0

### Bug summary

I'm creating a custom template for Umbraco 9, which among other things will have Contentment installed.

However, installing the Contentment NuGet package will cause Umbraco to fail on startup because it tries to run its upgrades in the Component here: https://github.com/leekelleher/umbraco-contentment/blob/0f60d6a2fd79a24174c5c5388a38c78be40363a2/src/Umbraco.Community.Contentment/Composing/ContentmentComponent.cs#L33-L34

This should probably check the RuntimeLevel before running... Or so I think. Will have a look at a proper fix tomorrow.

### Steps to reproduce

1. Create a blank Umbraco 9 project using dotnet new
2. Before running Umbraco for the first time, install Contentment
3. Then run Umbraco, it will crash and not open the installer

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

**Comment by arknu** [comment]
I have now provided a PR with the proposed fix here #137

**Comment by leekelleher** [comment]
@arknu Thanks for raising this, and submitting the PR! 🙏 

I'm juggling a heavy workload this week _(feels like most weeks recently),_ so I'll hopefully tackle this at the weekend.
I'm eager to get a final/stable release out that supports Umbraco v9, just bad timing that my workload got heavy during launch week. 🤷  _C'est la vie._

**Comment by arknu** [comment]
Thank you, @leekelleher. Will have a look at the multi-targeted branch. Very interested in seeing how that is set up.  And we all know how life suddenly gets busy - no worries there. Looking forward to the final release of this amazing package 😃

**Comment by leekelleher** [comment]
Closing off this ticket, as PR #137 has been merged in, and [Contentment v3.0.0-alpha006](https://github.com/leekelleher/umbraco-contentment/releases/tag/3.0.0-alpha006) has been release.
