### ISSUE TITLE
Contentment plugin return angular error when on azure load balancer

### ISSUE THREAD

**Issue by mitraganesh** [leekelleher/umbraco-contentment#138]
### Which Contentment version are you using?

1.4.3

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

8.3.6

### Bug summary

I am not sure this is a bug or not.

Using v1.4.3 contentment plugin in umbraco v8.6.3

Everything working fine in non load balancer server but not worked in my live load balancer server. I have a redirection rule in cms server

```
> <rule name="Redirect To Main" enabled="true">
>           <match url=".*"/>
>           <conditions logicalGrouping="MatchAll">          
>             <add input="{R:0}" pattern="^umbraco/?" ignoreCase="true" negate="true"/>            
>             <add input="{R:0}" pattern="^App_Plugins/?" ignoreCase="true" negate="true"/>
>             <add input="{R:0}" pattern="^umbraco/backoffice/?" ignoreCase="true" negate="true"/>
>             <add input="{R:0}" pattern="^backoffice/?" ignoreCase="true" negate="true"/>
>             <add input="{R:0}" pattern="^umbraco/Surface/?" ignoreCase="true" negate="true"/>
>             <add input="{R:0}" pattern="^umbraco/api/?" ignoreCase="true" negate="true"/>
>             <add input="{R:0}" pattern="^umbraco/assets/?" ignoreCase="true" negate="true"/>
>           </conditions>
>           <action type="Redirect" url="https://www.xxx.com.au/{R:0}"/>
>         </rule>
```
I am getting console error for datalist

The controller with the name 'Umbraco.Community.Contentment.DataEditors.ConfigurationEditor.Controller' is not registered.

And

The controller with the name 'Umbraco.Community.Contentment.DataEditors.DataList.Preview.Controller' is not registered.

### Steps to reproduce

NA

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Firefox, Safari, Microsoft Edge

**Comment by leekelleher** [comment]
> [_Cross referencing with forum post_](https://our.umbraco.com/packages/backoffice-extensions/contentment/contentment-feedback/107224-contentment-plugin-return-angular-error-when-on-azure-load-balancer), _(for future-proofing purposes)._

@mitraganesh Thanks for raising this.

I've haven't experienced this exact scenario before, so not sure if it's an issue with Contentment or the redirect rule you have in place?

Depending if you have `debug` mode enabled (in the Web.config), then either the JavaScript for Contentment would be loaded from `~/App_Plugins/Contentment/contentment.js` (if `debug=true`) or from ClientDependency's JavaScript bundle, (if `debug=false`), e.g. `~/DependencyHandler.axd?s=<big long querystring param>&t=Javascript&cdv=<version number>`.

Do you have any other packages installed? Are they experiencing a similar issue?

I suspect that you may need to add "DependencyHandler.axd" to your redirect rule?

**Comment by mitraganesh** [comment]
That's great!!!
DependencyHandler.axd to the redirection rule was solved the issue.
