### ISSUE TITLE
Data Sources: Add documentation for JSON Data

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#145]
I would like some help with contributions for the Data Sources documentation.

Here is the start of the page for JSON Data:
https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/data-sources/data-source--json.md

**Comment by zahertalab** [comment]
Hi
I'm interested.

**Comment by leekelleher** [comment]
@zahertalab - thanks, that's great! 👍 

In terms of an existing guide to follow, here's the one I did for the XML data-source. The JSON one should be in a similar nature... or I'm open to alternative suggestions.
<https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/data-sources/data-source--xml.md>

**Comment by zahertalab** [comment]
Ok, this is my first time to corporate. I'm just seeing how to use Github. For your issue, where I can start?

**Comment by leekelleher** [comment]
@zahertalab Firstly, just to clarify, this is documentation for a plugin feature for [Umbraco CMS](https://github.com/umbraco/Umbraco-CMS/).

If you aren't familiar with Umbraco or the packages ecosystem, this particular piece of documentation may not be an ideal starting point for you. But if you are familiar with Umbraco and packages, then great.

---

In terms of starting out with collaborating on GitHub, then a great place is GitHub's own documentation section, with lots of details on how the pull request system works.
<https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/about-collaborative-development-models>

I hope this helps.

**Comment by zahertalab** [comment]
I have previously written for WordPress and Drupal plugins. Can this help?
Thanks

**Comment by leekelleher** [comment]
@zahertalab Yes, that's cool. 👍

**Comment by zahertalab** [comment]
I have made a free Umbraco account, and I have found the Contentment package on the Umbraco website. But could not know how to install it, nor find where to implement installing code `Install-Package Our.Umbraco.Community.Contentment -Version 3.1.0`

**Comment by leekelleher** [comment]
Hi @zahertalab, is this on Umbraco Cloud? Do you know which version of Umbraco has been set up for you? (My assumption is the latest version v9.3.1).  I haven't used Umbraco Cloud in a while, so unsure how packages are installed on there these days. I shall ask someone from the Umbraco community who may have more information about it.

**Comment by greystate** [comment]
@zahertalab To install the package on Umbraco Cloud (for now) you will need to clone the repository and do the install on your local machine, via the command line (or, I think, the Package Manager in visual Studio). That is, if you're on Windows - if you're on a Mac, it'll take quite a little more effort (I'm on a Mac so I know it's possible at least 😁 )

**Comment by zahertalab** [comment]
Thank you. But I'm still not a developer for right now but a writer. What you tell me is near to some previous experiences such as installing Wordpress locally. I have tried to do what you tell me, but I still need more clarifications. Or just let me open your plugin in any way so that I can write the JSON document for you!

**Comment by zahertalab** [comment]
I have tried many instructions to install Umbraco locally using Visual Studio. But I get many errors, some of them getting solved via installing some .NET packages, but others non. And unfortunately, I couldn't even download the zip Umbraco package!

In all cases, I'm still interested to write the document. I watched some of your youtube videos, but seems they are not enough to make the JSON document.

I hope you have some other solution.

**Comment by leekelleher** [comment]
@zahertalab Thank you for persisting with this. I'm sorry that it's not been as straight forward as it could be.

No worries about the JSON documentation for my package, but I'd feel bad if it seems that Umbraco CMS has barriers to entry. Maybe the main Umbraco CMS documentation site would like your contributions? The open tickets are here: https://github.com/umbraco/UmbracoDocs/issues

**Comment by zahertalab** [comment]
Thank you. I hope to return soon, maybe I need to more strenth my skills more, or when these new barriers have been fixed.

**Comment by zahertalab** [comment]
![image](https://user-images.githubusercontent.com/85704521/156111062-b943513b-8186-46df-872d-a802d0294df6.png)

What I have messed up?

**Comment by greystate** [comment]
Hi @zahertalab

Couldn't help notice the typo in the **Database name** (`umbarco-9` instead of `umbraco-9`) - but then again, if it was mistyped creating the database, then that's the correct name, of course :)

I don't have a ton of SQL Server experience, but I have had to set a couple of sites up on a Windows laptop, and there I've had to use `\.SQLEXPRESS` as the **Server** - it's worth a try - otherwise I'd try with `localhost`, but that's just guessing, I'm afraid...

**Comment by nul800sebastiaan** [comment]
Hey there @zahertalab - I would love to help get Contentment installed for you, if you could invite me to your Cloud project:

![image](https://user-images.githubusercontent.com/304656/156141014-6f000ddd-9c3f-49e7-9a58-813b60b705e9.png)

I think I'll need Write & Admin permissions to do the install for you:

![image](https://user-images.githubusercontent.com/304656/156141104-5c3302fb-ee59-4d10-88cd-244648b1e937.png)

All I'll do is to install the package and push it to your Cloud trial and then you can move on and start playing with it. 

You can invite me on the email address in the second screenshot!

**Comment by zahertalab** [comment]
Thank you, Sebastiaan. I do have not the same exact GUI. But I hope this is the same essens.

![image](https://user-images.githubusercontent.com/85704521/156182614-02c90c87-1216-4c61-b699-8442dd39ec5a.png)

**Comment by nul800sebastiaan** [comment]
@zahertalab Thanks! Unfortunately that doesn't work quite the same! The UI you should be looking for is on https://umbraco.io - that's the only place that can give me access to be able to clone the project locally and push some changes. Can you try again from there?

Also: apologies, I meant to add that URL to the previous post, silly of me! 😅

**Comment by zahertalab** [comment]
Done! I hope eventually to start writing.

**Comment by nul800sebastiaan** [comment]
@zahertalab Great, that worked! You now have Contentment installed!

![image](https://user-images.githubusercontent.com/304656/156207632-ac267ec6-1288-4f95-9c32-780587af61d8.png)

FYI: The Cloud team is very keen to work on the feature where you can install NuGet packages on Cloud, without having to clone it down and run it locally first. They're not there yet, but will get there eventually!

**Comment by zahertalab** [comment]
I have finished it right now. If it's OK, let me complete the other data types docs before the cloud Umbraco demo ends!

**Comment by zahertalab** [comment]
The "file system" doc is now ready to review:
https://github.com/zahertalab/umbraco-contentment/blob/develop/docs/data-sources/data-source--file-system.md

**Comment by leekelleher** [comment]
Closing this ticket, pull request #203 has the updated documentation.

@zahertalab Issue #144 covers the File System documentation request. If you would like to send a pull request over for me to review and merge in, thank you.
