### ISSUE TITLE
Data Sources: Add documentation for Number Range

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#147]
I would like some help with contributions for the Data Sources documentation.

Here is the start of the page for Number Range:
https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/data-sources/data-source--number-range.md

**Comment by zahertalab** [comment]
Here is it. But also could not find the "pull request" button as the first time:
https://github.com/zahertalab/umbraco-contentment/blob/develop/docs/data-sources/data-source--number-range.md
