### ISSUE TITLE
Umbraco.Community.Contentment.DataEditors.Notes.Controller missing import in package file

### ISSUE THREAD

**Issue by konius** [leekelleher/umbraco-contentment#168]
### Which Contentment version are you using?

3.0.0-alpha006

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

v9

### Bug summary

The package.manifest file has no notes.js controller import resulting in console error.

![Screenshot 2021-10-07 140519](https://user-images.githubusercontent.com/3933562/136372434-4aa1d192-e9bb-4093-8023-cbd1eb733542.jpg)

### Steps to reproduce

Open Notes datatype in the back office and see console.

### Expected result / actual result

No issues in console.

### Do you have Umbraco ModelsBuilder enabled?

- [ ] Yes, it is enabled.

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by leekelleher** [comment]
@konius Thank you for reporting this, it is a bug.

The immediate workaround is to add `"~/App_Plugins/Contentment/editors/notes.js",` to the `package.manifest` file.

For whatever reason, I missed it from here: https://github.com/leekelleher/umbraco-contentment/blob/3.0.0-alpha006/src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/package.manifest#L43

**Comment by leekelleher** [comment]
I'm closing this issue off. Resolved with [Contentment v3.0.0-beta001](https://github.com/leekelleher/umbraco-contentment/releases/tag/3.0.0-beta001).
