### ISSUE TITLE
Lang folder case sensitive on Linux

### ISSUE THREAD

**Issue by dan-hammond** [leekelleher/umbraco-contentment#198]
### Which Contentment version are you using?

3.0.1

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

9.3.0

### Bug summary

Hi,

Thank you for this package, it's a great collection of functionality.

The `lang` folder in `App_Plugins/Contentment` has a lower case L, which causes it to be ignored on Linux systems. 

Here is the relevant note about this case sensitivity in the Umbraco documentation:
[https://our.umbraco.com/documentation/extending/language-files/#package-language-files](https://our.umbraco.com/documentation/extending/language-files/#package-language-files)

### Steps to reproduce

- Create a new Umbraco 9 solution and install the latest version of Contentment
- Build the solution
- Note that `App_Plugins/Contentment/lang` has the lower case L

### Expected result / actual result

The Lang folder should be `App_Plugins/Contentment/Lang`

### Do you have Umbraco ModelsBuilder enabled?

- [ ] Yes, it is enabled.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by leekelleher** [comment]
@dan-hammond Thanks for raising this. First time I'm hearing about the Lang folder name casing. I'll get it corrected in the next release. 👍

**Comment by leekelleher** [comment]
@dan-hammond I've corrected the casing, it'll be in the next release.

I've gotta say, it's now messing with my OCD! 🤣 
![Contentment App_Plugins folder items](https://user-images.githubusercontent.com/209066/153588667-95a2d138-18c0-4759-9601-e7826f876b19.png)

**Comment by dan-hammond** [comment]
Nice one, thank you! Agreed, I think I would've preferred it as `lang` as well. Most of the Umbraco packages I've used have theirs as lower case, and Umbraco's own one is lower case, so it's an odd choice from HQ I think!

**Comment by leekelleher** [comment]
There was a discussion over on Umbraco's repo about formalising naming conventions.
https://github.com/umbraco/Umbraco-CMS/discussions/10638

I'd prefer all the web/asset files to be kebab-case (lowercase). The capitalisation feels that it comes from general Microsoft/.NET/C# class name conventions.

**Comment by mattbrailsford** [comment]
Lol, I just made a PR for this as I outright refuse to name my `lang` folder `Lang` 😂

https://github.com/umbraco/Umbraco-CMS/pull/11985
