### ISSUE TITLE
Enum DataType with no selection results in extremely large serialised data for Umbraco

### ISSUE THREAD

**Issue by robertjf** [leekelleher/umbraco-contentment#206]
### Which Contentment version are you using?

3.1.0

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

9.3.1

### Bug summary

We are building a site that implements the Umbraco Content Blocks datatype for many pages, and recently we've hit upon an issue when saving one of the pages where the green Save/Submit button goes from the busy state to a green error state ('X).

Investigating in DevTools showed that the controller was returning a 413 error, consistent with [this issue - New default 30 MB (~28.6 MiB) max request body size limit](https://github.com/aspnet/Announcements/issues/267) back in 2017.  When inspecting the headers, the `content-length` was 33581128 bytes, or over the 30MB limit of the default max request body size.

Further inspection of the call by setting breakpoints in the code and rendering the data out with `Utilities.toJson` resulted in a string size of `33.6 MB`!

I was able to download and inspect the json file, and the only abnormality was this:

```

                    {
                      "contentTypeKey": "07a02735-44df-48f1-a572-1212cfb2b7e4",
                      "udi": "umb://element/e3f318e96ba143de883df144b6bebe48",
                      "justify": ""\"\\\"\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"Center\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\"\\\\\\\"\\\"\"",
                      ""underlinedText": "",
                      "underlineColour": {
                        "value": "ff80a9",
                        "label": "Love",
                        "sortOrder": 3,
                        "id": "4"
                      },
                      "underlineStyle": ["ChalkLine1"],
                      "blockPartitionStyle": ""
                    }
```

the extra `\` in the justify data occurred twice, and when I deleted the data only out, the file size dropped from 32MB to 38kb.

It looks like when the data is written back, there's an issue where it's being incorrectly serialized/deserialised, and each save is compounding the problem.  The data probably should be just `"Center"` in the example above.

Here's the configuration of the enum data type:
![image](https://user-images.githubusercontent.com/818101/157378569-eb7a05d5-886a-45e2-8435-89a08a9b2662.png)

![image](https://user-images.githubusercontent.com/818101/157378539-ef425e7e-5e0c-45e3-bf66-cb6a7180d924.png)

### Steps to reproduce

See above.

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by leekelleher** [comment]
@robertjf Thanks for reporting this, I'll try to reproduce the issue.

To clarify, is "Umbraco Content Blocks" the Umbraco Block List Editor?

**Comment by leekelleher** [comment]
I can't reproduce this with Umbraco v9.0.0 and latest (bleeding-edge) Contentment. _(I'm using v9.0.0 as the baseline for my demo, since it's the minimum dependency)._

I'll spin up a v9.3.1 site next, see if there have been any differences to Block List editor. My gut feeling is that this may be related to #200 - which turned out to be a regression bug in Umbraco v9.3.0.

**Comment by robertjf** [comment]
Hey @leekelleher - it could very well be related, I did notice that the values were all lost when I went to edit them; I'm doing some more testing myself to see what happens when I re-set the values.

**Comment by robertjf** [comment]
oh, and yes, the Block List Editor, correct.

**Comment by robertjf** [comment]
@leekelleher ok, so it seems that now that I've gone through and re-assigned values to the properties and saved the content, it's resolved.  What I suspect, is that prior to using the Enum Picker, I had a regular radio button list and so the data may have been invalid to begin with - now that I've re-saved with the correct data, it seems to be behaving.

**Comment by leekelleher** [comment]
@robertjf Okay, glad to hear that it seems to be working now. 👍  I'll close off this issue for now, but if it creeps up again please do feel free to re-open it. Bit concerning if there's a 30Mb+ JSON payload happening somewhere. 😬 Thanks again for reporting it.
