### ISSUE TITLE
The type or namespace name 'SocialLink' does not exist in the namespace 'Umbraco.Cms.Core.Models.PublishedContent'

### ISSUE THREAD

**Issue by Wiggee11** [leekelleher/umbraco-contentment#244]
### Which Contentment version are you using?

4.1.1

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

10.0.1

### Bug summary

Get Visual Studio build errors after creating a property with the Contentment SocialLinks property editor.

### Steps to reproduce

- Installed Contentment v4.1.1
- Created a prop using Umbraco.Community.Contentment.SocialLinks
- The website and prop run fine
- When I rebuild Visual Studio I get "The type or namespace name 'SocialLink' does not exist in the namespace 'Umbraco.Cms.Core.Models.PublishedContent'" error in the generated model

### Expected result / actual result

Expected result - Application should build fine after creating a property using the Contentment SocialLinks property editor

Actual result - Application does not build

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome

**Comment by leekelleher** [comment]
@Wiggee11 Thanks for raising this.

Is the Visual Studio project the website itself, or a separate class library? If it's a class library is it referencing the `Our.Umbraco.Contentment.Core` nuget package?

**Comment by Wiggee11** [comment]
The embedded ModelsBuilder is set to build to a separate class library.

Adding the Core package resolved the issue.

Thanks for responding so quickly.

**Comment by leekelleher** [comment]
@Wiggee11 Cool, no problem! Glad it was quickly resolvable. 👍
