### ISSUE TITLE
Proposal: UI-tweaks for Data List with Item Picker (Multiple)

### ISSUE THREAD

**Issue by enkelmedia** [leekelleher/umbraco-contentment#256]
### Which Contentment version are you using?

4.1.5

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

10.1.0

### Bug summary

We're using a Data List configured with a Item Picker that allows for multiple items to be selected.

This used to look something like this:
![old](https://user-images.githubusercontent.com/1782524/191235084-46ee8eac-8e8b-4b40-a1b9-9117646757d8.PNG)
Here the gray color indicates clearly that an item is not selected but due to Umbraco style-updates it looks like this out of the box now:

![now](https://user-images.githubusercontent.com/1782524/191235402-96101631-1515-4055-a184-3ab556c55dd7.PNG)

It looks kind like everything i selected, how ever when an item is actually selected it becomes more clear that the others where not:

![now2](https://user-images.githubusercontent.com/1782524/191235507-6a911787-f4a1-486a-a0f6-b2ca63807003.PNG)

I'm proposing that the icon should be removed when an item is not selected making it look like this:

![future](https://user-images.githubusercontent.com/1782524/191235590-cea54a75-b27b-4a1e-9baf-b0a239a0a72c.png)

If this is a good idea I'm happy to help out.

### Steps to reproduce

Setup a Data List of type "Item Picker" and allow for multiple items to be selected. Click the "Add"-button to see this in the editor sliding in from the right.

### Expected result / actual result

It should be very clear that none of the items in the list is selected.

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome

**Comment by leekelleher** [comment]
@enkelmedia Thanks for raising this. I was reusing Umbraco's `<umb-checkmark>` directive, which only had the `icon-check` icon displayed (no toggle). I agree with your suggestion and have amended the markup accordingly. Fixed in commit 5cc1c50f32de6e7dc30cb22bb2fd5874d742a36e. I'll schedule a patch release soon.

**Comment by enkelmedia** [comment]
@leekelleher I see! Thanks for looking into this so fast =D No need to stress with the patch-release I just wanted to raise the issue so that there could be a small improvement for the editors =D 

Cheers!
