### ISSUE TITLE
Missing DataType Icons on Umbraco Cloud?

### ISSUE THREAD

**Issue by hfloyd** [leekelleher/umbraco-contentment#260]
### Which Contentment version are you using?

4.1.5

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

10.2.0

### Bug summary

Locally, this isn't an issue, but when deployed to Umbraco Cloud, the datatypes seem to be missing their icons:

**In Chrome:**
![image](https://user-images.githubusercontent.com/1252593/192590998-7975a6ad-4add-494a-a3fd-23f293d4b4f5.png)

**In Firefox:**
![image](https://user-images.githubusercontent.com/1252593/192591798-cd5e20c8-7696-4743-a354-92b12d9ed628.png)

### Steps to reproduce

Deploy Contentment + some created Contentment DataTypes to Umbraco Cloud. Check the Settings> DataTypes tree.

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by leekelleher** [comment]
Hi @hfloyd, thanks for raising this issue.

My first thought was that the FontAwesome font hasn't been loaded into the browser properly?
Although, based on the Firefox screengrab, I can see that the `font-awesome.min.css` has been loaded, (as the tiny `F0 CA` codes come from the FontAwesome CSS), but that might also mean that the actual web-font file hasn't been loaded in.

Do you have any errors in your browser console?

**Comment by hfloyd** [comment]
After I posted, I did see a 500 error related to "/sb/umbraco-backoffice-css.css.v637998978402764614", which I am trying to resolve now. If I can get that error to disappear, perhaps it will resolve the icon issue. I will report back.

**Comment by leekelleher** [comment]
Hi @hfloyd, was this issue resolved, or something we need to look into?

**Comment by hfloyd** [comment]
@leekelleher I got this resolved. I think it was caused by the back-office "smidging" of all App_Plugins - if any of the CSS files has an issue, it stops loading all future files. Contentment wasn't the issue - it was a different file blocking the loading. I'll close this now.
