### ISSUE TITLE
Umbraco Content Types DataSource does not use translations

### ISSUE THREAD

**Issue by jerpenol** [leekelleher/umbraco-contentment#319]
### Which Contentment version are you using?

4.4.3

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

11.3.1

### Bug summary

Not sure if this is a bug or not, but when I create a DataList property with the "Umbraco Content Types" datasource, it shows the original contenttype title instead of the translated version.

### Steps to reproduce

- Create a DataList datatype "ContentTypePicker", that uses the "Umbraco Content Types" datasource and list editor "Item Picker"
- Create a ContentType "#Test1", with a property of type "ContentTypePicker" called "TestPicker"
- Add a Translation to the TranslationDictionary with key "Test1" and value in default language "Translated Test 1"
- Create a page of type "#Test1"
- When you try to add a ContentType to "TestPicker" property it will display the avialable ContentType as "#Test1" instead of "Translated Test 1"

### Expected result / actual result

**Expected**: The ContentTypes in the property display based on their translation(s)
**Actual**: The ContentTypes in the property are display as is (with #)

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by leekelleher** [comment]
Thanks for raising this @jerpenol.

It's not a bug as such, as the code for the "Umbraco Content Type" data-source makes no attempt to localize the label.

https://github.com/leekelleher/umbraco-contentment/blob/4.4.3/src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/UmbracoContentTypesDataListSource.cs#L136

It is a good feature suggestion. I'm not entirely sure how Umbraco handles this internally, hopefully there will be an API or code to reuse.  I'm open to a contribution for this feature.
