### ISSUE TITLE
Can't use Block List editor (inline) inside a Contentment Block List

### ISSUE THREAD

**Issue by drpeck** [leekelleher/umbraco-contentment#330]
### Which Contentment version are you using?

Latest

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

12.0.0

### Bug summary

I have an Umbraco Block List, inside of which is a Block with a Contentment Block List, inside of which is Block is an Umbraco Block List. The latter Block List fails to load with the console error "Could not find umbVariantContent in the $scope chain".

A similar issue has been reported relating to the Umbraco Block List editor, so I don't know if Contentment has the ability to workaround this issue or not.
https://github.com/umbraco/Umbraco-CMS/issues/10085

### Steps to reproduce

Setup a Block Lists as described, although I suspect it the top level Umbraco Block List is irrelevant.

### Expected result / actual result

I expected the editor to load instead of
![image](https://github.com/leekelleher/umbraco-contentment/assets/1196047/7fccf41e-c66c-4537-9361-bf5b36d7e23c)

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by leekelleher** [comment]
@drpeck Thanks for raising this.

For my own clarification, the hierarchy is...

- Block List
  - Content Blocks
    - Block List

I can't recall ever trying that scenario. My initial thought would be why have a Content Blocks in the middle? but I'm sure you have your reasons. 😊 

I do know about the Block List requirement on `umbVariantContent`, which I've encountered when trying to use it outside the Content section, e.g. Media, Members, and custom sections, (a la Konstrukt).

My gut feeling is that Block List wouldn't work inside a Content Blocks.  I'm not sure what could be done to resolve it (within Content Blocks).  Open to suggestions.

**Comment by drpeck** [comment]
That is the hierarchy and the reason for the data type choice is suitability of UI for the data - generally preferring Content Blocks but no support for inline rendering.

I've no clue how to resolve it but knew that there would be a chance that you would know how. My best guess would be if it might be possible to mock the service enough to avoid the error, but that probably unrealistic.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leekelleher** [comment]
> no support for inline rendering

@drpeck I'm curious what you mean by "inline rendering"? As in previews or the Nested Content style of inline editing?

re: mocking `umbVariantContent`, I had looked at this a while back, but it's a beast - it's the functionality that handles the multi-lingual variants. 🤯
