### ISSUE TITLE
Layout issues with checkboxes and radio buttons in Umbraco 8.7

### ISSUE THREAD

**Issue by arknu** [leekelleher/umbraco-contentment#36]
### What is the current behavior?
In Umbraco 8.7 there are layout issues with checkboxes and radio buttons in the DataList editor:
![image](https://user-images.githubusercontent.com/4654741/91150270-776b9200-e6bc-11ea-8065-59ff8fa086a4.png)
![image](https://user-images.githubusercontent.com/4654741/91150446-b13c9880-e6bc-11ea-8012-59e4c41f996b.png)

This also affects the prevalue editor for the Bytes datatype:
![image](https://user-images.githubusercontent.com/4654741/91150686-011b5f80-e6bd-11ea-89e0-44c64db4f94d.png)

### What is the expected behavior?
Checkboxes and radio buttons should be displayed correctly

### Please tell us about your set-up:

- Contentment version: 1.0.0
- Umbraco version: 8.7.0-rc
- Browser: Edge 86

**Comment by leekelleher** [comment]
@arknu Thank you, I appreciate you taking the time to raise this.

I'd already spotted it and have a fix prepared in commit 3e89d1e3dc817ffdfc27b6808756702ee8822bd4. It'll be part of a v1.0.1 patch release. #33 

I'll close this ticket off.
