### ISSUE TITLE
Umbraco 13, `ToArtifact` method signature mismatch

### ISSUE THREAD

**Issue by huwred** [leekelleher/umbraco-contentment#366]
### Which Contentment version are you using?

4.5.0

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

13.0.0-rc1

### Bug summary

When attempting to run Umbraco after installing contentment or the clean starter kit (which depends on contentment) I get the following errors

### Steps to reproduce

Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.5.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.5.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.5.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Interestingly Paul Seal does not get this issue with his clean starter kit which uses contentment

### Do you have Umbraco ModelsBuilder enabled?

- [ ] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by huwred** [comment]
seems it was a nuget cache issue, I cleared my local cache and tried again and all now working

**Comment by leekelleher** [comment]
Hi @huwred, good to hear it was resolvable. 👍

**Comment by leekelleher** [comment]
@OwainJ I wasn't aware that v13-RC2 had been release, (not sure how I missed it, I blame the lack of umbraCoffee! ☕)

Turns out that there's a method signature change to `ToArtifact()` between v13-RC1 and v13-RC2.
https://github.com/umbraco/Umbraco-CMS/compare/release-13.0.0-rc1...release-13.0.0-rc2#diff-27975a4ec9d6d75aaaffce8ed8b4e4259989327ecce6df8cb8a032064400c9f1

I'll look to get this patched up in Contentment. (I'm not sure what else to suggest in the meantime, sorry).

**Comment by leekelleher** [comment]
@OwainJ Just to let you know that I've patched this up, (in commit 107ef2c7203e9477f231c3eaa63137c6145d2b00), by adding specific support for v13. I will put this out as a new minor release for Contentment, but I'm hesitant to do this before the final v13 release date, (14th Dec), as I'm unsure if there'll be any other breaking-changes made between now and then.

**Comment by OwainJ** [comment]
No worries, I'm in no rush to get it to work for the v13 RC personally, just happens that the Clean starter kit is my usual go-to when testing RCs and Preview versions :)

**Comment by marcusjm** [comment]
Any chance for a mini pre-release on this package? Just wondering :).

**Comment by marcusjm** [comment]
> @OwainJ Just to let you know that I've patched this up, (in commit [107ef2c](https://github.com/leekelleher/umbraco-contentment/commit/107ef2c7203e9477f231c3eaa63137c6145d2b00)), by adding specific support for v13. I will put this out as a new minor release for Contentment, but I'm hesitant to do this before the final v13 release date, (14th Dec), as I'm unsure if there'll be any other breaking-changes made between now and then.

Great if a pre-release could be pushed anyway. If possible.

**Comment by bielu** [comment]
@leekelleher is there any chance for pre-release, or should I do for now my github fork and release it there with not collidating prefix? :)

**Comment by bielu** [comment]
@marcusjm i release pre-release on my github feed, feel free to use.
@leekelleher if I will find any issues will send pr against your v13 branch :)

**Comment by marcusjm** [comment]
> @marcusjm i release pre-release on my github feed, feel free to use. @leekelleher if I will find any issues will send pr against your v13 branch :)

Sorry for being blind but where is this private nuget feed?

**Comment by bielu** [comment]
@marcusjm https://nuget.pkg.github.com/bielu/index.json I think there is way to find on profile, but seems like i forgot paste the link ;)

**Comment by marcusjm** [comment]
Is it private? Seems I get authentication issues.

**Comment by bielu** [comment]
It is public feed you should be to authenticate against it with Github PAT (github require PAT Auth to even public feeds)

**Comment by marcusjm** [comment]
I know but I thought it was.

**Comment by AaronSadlerUK** [comment]
@leekelleher Any chance of the minor being released?

I'm trying to ensure my starterkit works for the V13 release date, but this is blocking me

**Comment by leekelleher** [comment]
Unfortunately, due to other commitments, I wont have time before Thursday to get a pre-release out. I am still aiming to get a v4.6.0 prepared for Umbraco v13.0.0 (on Thursday).  I appreciate that the timing sucks, but I couldn't afford to put the time/effort into keeping up with the multiple v13 RC releases (and potential breaking-changes).

**Comment by leekelleher** [comment]
Contentment v4.6.0 is out!
https://github.com/leekelleher/umbraco-contentment/releases/tag/4.6.0
