### ISSUE TITLE
backoffice/Contentment/DataPickerApi/Search 404 when using in UI builder?

### ISSUE THREAD

**Issue by brannmark** [leekelleher/umbraco-contentment#368]
### Which Contentment version are you using?

4.5.1

### Which Umbraco version are you using? For example: 8.14.1 - don't just write v8

12.3.1

### Bug summary

Setup a custom DataPicker source that querys a custom service for items. But cant get it to work due to backoffice/Contentment/DataPickerApi/Search throws an 404 error in the backend.

### Steps to reproduce

![DataType](https://github.com/leekelleher/umbraco-contentment/assets/1013748/48ed2d3a-a5a9-475e-9a09-faf8fc1d6695)
![Error](https://github.com/leekelleher/umbraco-contentment/assets/1013748/6f1ee1b5-bc37-4edf-82df-76eb7c2b338e)

### Do you have Umbraco ModelsBuilder enabled?

- [ ] Yes, it is enabled.

**Comment by brannmark** [comment]
Note, when running in debug, it doesn't hit breakpoints in custom datasource on GetItemsAsync or SearchAsync.

**Comment by leekelleher** [comment]
Hi @brannmark, thanks for reporting this. I haven't used UI Builder (or Konstrukt) myself, so unsure what the differences are between using it on content nodes.

Is this on Umbraco Cloud, or self-hosted?

Do you know if the Data Picker works in the the content section of your Umbraco instance?
Then I can rule out whether it's a UI Builder or Umbraco Cloud issue.

**Comment by brannmark** [comment]
Self-hosted, on localhost currently. 
Dont have any content in the umbraco right now. Only a UI builder section.
See in network that the data picker tries to make a get to this url:
https://localhost:XXXXX/umbraco/backoffice/Contentment/DataPickerApi/Search?dataTypeKey=00000000-0000-0000-0000-000000000000&id=9507&pageNumber=1&pageSize=20&query= and receives a 404 error. Tried with a default datasource like .net countries, same error.

**Comment by leekelleher** [comment]
Thanks @brannmark, this is helpful. 🙏
I can see it's the `dataTypeKey` is an empty GUID, which is why it's returning a 404.

My initial thought is that UI Builder is missing extra metadata (at property-editor level), but I'll investigate the Data Picker code, just in case anything is amiss.

**Comment by brannmark** [comment]
Took the guid from the datatype in Umbraco and tried running the url with the key, no luck either,
https://localhost:XXXXX/umbraco/backoffice/Contentment/DataPickerApi/Search?dataTypeKey=847a739f-58b6-467b-b6cd-06a4c34471d1&id=1&pageNumber=1&pageSize=20&query=

Receives this response with a 417:
)]}',
{"Type":null,"Title":null,"Status":417,"Detail":null,"Instance":null,"Extensions":{"traceId":"00-96d8f8981f15951290fd6a589e8a62aa-35c107ac12682b67-00"}}

**Comment by leekelleher** [comment]
@brannmark When trying to access the API URL directly in the browser, it's expected to throw a [417 error code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/417), as the [endpoint is marked as needing to be authorized](https://github.com/leekelleher/umbraco-contentment/blob/4.5.1/src/Umbraco.Community.Contentment/DataEditors/DataPicker/DataPickerApiController.cs#L32) from a backoffice request, (Umbraco sends extra auth/token meta-data to prevent non-backoffice access) - frustrating for debugging, but secure.

I've had a look at Data Picker's code for populating the `dataTypeKey` value, it uses `$scope.model.dataTypeKey`...
https://github.com/leekelleher/umbraco-contentment/blob/4.5.1/src/Umbraco.Community.Contentment/DataEditors/DataPicker/data-picker.js#L114
...which I can only assume that UI Builder (Konstrukt) isn't populating the value of `$scope.model.dataTypeKey.

There isn't much I can do within Contentment (at Data Picker level), so an issue would need to be raised on the [UI Builder issue tracker](https://github.com/umbraco/Umbraco.UIBuilder.Issues/issues). Feel free to point the issue back here, I'm happy to discuss further with the HQ team.
