### ISSUE TITLE
Missing "Lee was Here" in Safari :)

### ISSUE THREAD

**Issue by greystate** [leekelleher/umbraco-contentment#37]
This is not a big issue — I've just noticed a missing image on some Contentment screens and always attributed it to a network error or similar, but today I got curious and found out what was happening.

Here's a screenshot from **Safari 13.1.2**:

<img width="381" alt="Screenshot 2020-09-01 at 15 50 41" src="https://user-images.githubusercontent.com/5463/91861036-a493e380-ec6c-11ea-9b24-768dc0af23f2.png">

The reason the image isn't loading is because it's a WebP image which Safari (currently) doesn't support.

**Comment by leekelleher** [comment]
@greystate Thanks for flagging this up.

...and there I was thinking WebP had wider support! 🤦‍♂️ <https://caniuse.com/#feat=webp> - noted Safari is for the v14 Tech Preview.

I'll swap it over to be PNG format for the next release. 🚀

**Comment by greystate** [comment]
(Happy to submit a PR by the way :)

**Comment by leekelleher** [comment]
@greystate Thanks for offering. 🙏  I've already done it (locally).
