### ISSUE TITLE
Contentment can cause performance issues

### ISSUE THREAD

**Issue by bielu** [leekelleher/umbraco-contentment#377]
### Which Contentment version are you using?

Latest v4

### Which Umbraco version are you using? For example: 10.3.2 - don't just write v10

v10,v13

### Bug summary

So when debugging one of sites, i noticed that umbraco had performance issues and found this 2 threads:
https://github.com/umbraco/Umbraco-CMS/issues/14936
https://github.com/umbraco/Umbraco-CMS/issues/14842
As soon this changes will be introduced I will introduced them in contentment as well towards v5 build, as i doubt it gonna be backported to v10-v12. 
Affected classes:

1. ContentBlocksDataValueEditor
2. UmbracoImageCropDataListSource

### Steps to reproduce

Read issues related to umbraco

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

**Comment by leekelleher** [comment]
@bielu Thanks for reporting this. The linked issues have quite a lot to read up on and digest. From what I gather it's any call to a data service layer, e.g. `IDataTypeService` that will cause the severe bottlenecks when there are many document variants and several properties that call those services.

**Comment by bielu** [comment]
@leekelleher yep :), it is related to implementaiion of application cache of umbraco(used in data repositories) which makes speaking to memeory cache extremly expensive 😢

**Comment by bielu** [comment]
hey @leekelleher, 
Finally with HQ we agreed to way to implement fix, so I will be addressing Pr as soon as 13.2 rc will be released :)

**Comment by leekelleher** [comment]
@bielu Thanks for the update! 👍  Is this the corresponding PR? https://github.com/umbraco/Umbraco-CMS/pull/15731

The the fix for Contentment is to make use of the new `IDataTypeConfigurationCache`, then I'd probably be looking to bump the minimum Umbraco dependency to v13.2.0 on the `dev/v5.x` branch. Unless if you have a backwards-compatible fix in mind for v4.x?

**Comment by bielu** [comment]
@leekelleher yes it is  corrected PR.
In theory we can do in backwards compatible way for .net <8 but it would be breaking change for anything .net 8 based. 
so I am assuming best will be target v5? also what would approx date for v5 to be released at least as alpha?

**Comment by leekelleher** [comment]
@bielu Contentment v5 is pretty much ready for an initial release, (as there are no features holding it back except my own time/effort to release it).

**Comment by leekelleher** [comment]
Fixed in #382, to be released in upcoming Contentment v5.
