### ISSUE TITLE
Decoupling from AngularJS

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#38]
Taking lead from the [**Start decoupling from AngularJs #7718**](https://github.com/umbraco/Umbraco-CMS/issues/7718) ticket on the Umbraco CMS repo. I'd like Contentment to follow the same approach.

Using GitHub's search, these are the code files containing `// TODO: Replace AngularJS dependency.` that I've littered throughout my codebase. <https://github.com/leekelleher/umbraco-contentment/search?q=TODO+AngularJS+dependency&unscoped_q=TODO+AngularJS+dependency&type=Code>

**If anyone would like to help with this ticket, please don't interpret it as a whole task - any small incremental amends are warmly welcome.**

**Comment by Matthew-Wise** [comment]
The two instances in the search results now have Utilities implementations in Umbraco's code base, Should I use those which would mean a new minimum requirement for contentment

**Comment by leekelleher** [comment]
@Matthew-Wise Cool.  The only issue is that Contentment v1.x builds against Umbraco v8.6.1.

My aim is to bump the Umbraco dependency up to v8.10.0 _(due for release tomorrow),_ for a Contentment v2.x (breaking-change release).

I haven't set-up any branches for v2.x yet, so this issue is kinda stuck in limbo until I do that. Although in the meantime, if you are eager, then you can work against the `develop` branch and I'll re-target any PRs afterwards - just means that there'll be a delay with me merging it in.

**Comment by leekelleher** [comment]
**Update:** You can use the `dev/v2.0` branch as the base for these changes.  I haven't bumped up the Umbraco minimum dependency version in `dev/v2.0` yet, but will do soon - it shouldn't prevent you from making any code amends.

_FYI, I had to do a rebase (and forced push) on the `dev/v2.0` branch, I'm not 100% if that mucks up your fork at all? So apologies if any headaches happen._

**Comment by leekelleher** [comment]
Closing this issue, resolved with PR #63 - thank you @Matthew-Wise! 🌟
