### ISSUE TITLE
Decoupling from Underscore.js

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#39]
Taking lead from the [**Some decoupling from underscorejs #7731**](https://github.com/umbraco/Umbraco-CMS/issues/7731) ticket on the Umbraco CMS repo. I'd like Contentment to follow the same approach.

> Also, relevant reading... [**You don't (may not) need Lodash/Underscore**](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore).

Using GitHub's search, these are the code files containing `// TODO: Replace Underscore.js dependency.` that I've littered throughout my codebase. <https://github.com/leekelleher/umbraco-contentment/search?q=TODO+Underscore+dependency&unscoped_q=TODO+Underscore+dependency&type=Code>

**If anyone would like to help with this ticket, please don't interpret it as a whole task - any small incremental amends are warmly welcome.**

**Comment by greystate** [comment]
Would the idea be the same as has been started for Umbraco (i.e., to replace Underscore with e.g. a `Utilities` object/class?)

**Comment by leekelleher** [comment]
Yes. I'm not sure which Umbraco version the `Utilities` helper is introduced in. (I assume 8.7.0, I'll check tomorrow). Either way, I'm happy to bump up the min version.

**Comment by leekelleher** [comment]
@greystate Confirmed that `Utilities` will be part of Umbraco 8.7.0. (ref: <https://github.com/umbraco/Umbraco-CMS/pull/7738>)

Currently, Contentment is built against v8.6.1. I'm happy to bump this up to v8.7.0 once it is released, which would be for whatever the next Contentment version would be, either v1.1.x or v1.2.x.

I guess in the meantime, it's checking if there are any Underscore helpers used that could be replaced with native functions?

**Comment by leekelleher** [comment]
Closing this ticket. It'll be covered (and any further discussion) on PR #64.
