### ISSUE TITLE
Data List, Examine Query - passing language variant to get items call.

### ISSUE THREAD

**Issue by andrea-mcdonald** [leekelleher/umbraco-contentment#397]
### Which Contentment version are you using?

4.4.4

### Which Umbraco version are you using? For example: 13.2.1 - don't just write v13

 11.4.2

### Bug summary

In the backend we are using a Contentment datalist which populates the data source from an Examine query, we have an issue with language variants where the field will randomly clear itself

Sometimes we can have several of us looking it at in the backend, and this title field will show up blank to use of, and another will see the correct issue

### Steps to reproduce

Create an article on a site using multiple language variants, create the content in the local variant, publish all language variants

Make sure the language variant you want to test has a datalist populating its data from Examine, and that the data is pulling through

Keep adding language variants and repeating until it starts to fail and you see the datalist empty

### Expected result / actual result

The datalist should return the data from Examine, unless it is not in the Examine index itself

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome, Edge, Firefox, Safari

**Comment by leekelleher** [comment]
@andrea-mcdonald, thanks for raising this. I don't have an immediate answer, I will get back to you once I have time to understand the scenario more.

Cross-linking with a related discussion: https://github.com/leekelleher/umbraco-contentment/discussions/396

**Comment by leekelleher** [comment]
@andrea-mcdonald Apologies for the delay in getting back to you. I've left a reply on the related discussion page, https://github.com/leekelleher/umbraco-contentment/discussions/396#discussioncomment-9470495.

_TL;DR, quick answer is that it isn't currently possible with the Data List editor to access the active variant/culture._

I'll close off this ticket, and happy for the discussion to continue on: https://github.com/leekelleher/umbraco-contentment/discussions/396
