### ISSUE TITLE
JsonDataListSource - Get "key" name value in JSONPath

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#40]
https://github.com/leekelleher/umbraco-contentment/blob/8e3312ac587fa6bd245d2cdd637ae7fedfaed618/src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/JsonDataListSource.cs#L130-L132

I openly admit, JSONPath isn't clicking with me. I struggle to mentally apply my XPath knowledge to JSONPath.

With the `JsonDataListSource`, something that we can't currently do is get the value from a property name, e.g. "key".

There is a project called [JSONPath Plus](https://github.com/s3u/JSONPath) that extends on the JSONPath spec. This includes a "`~`" expression to retrieve key names. However the JSONPath Plus library is in JavaScript, and Contentment is querying the JSON on the server-side (C#/.NET).

I wonder if something similar could be implemented, maybe to extend JSON.NET's `SelectTokens` method or for alternative way to extract the keys?

**Comment by RichGreen** [comment]
Wish I could help!

**Comment by greystate** [comment]
Me too - I have also felt a heavy wall against my forehead whenever I tried to make sense of JSONPath ...

**Comment by leekelleher** [comment]
Closing this ticket off.

It's still something that I'd like help with to solve, but I guess that's more my _developer's itch_ than my real-world _need_ for it... and given that no one has requested this _(as a missing feature)_ since the initial release, I suspect folk aren't generally bothered about it. 🤷 😄 

However if someone is bothered enough, then please feel free to re-open this ticket.
