### ISSUE TITLE
package.json and related files are showing in solution after install

### ISSUE THREAD

**Issue by D-Inventor** [leekelleher/umbraco-contentment#400]
### Which Contentment version are you using?

5.0.0

### Which Umbraco version are you using? For example: 13.2.1 - don't just write v13

13.3.0

### Bug summary

After installing, at least the package.json file and package-lock.json of contentment are referenced inside my project. This is likely because this version of Contentment uses a razor class library:
![image](https://github.com/leekelleher/umbraco-contentment/assets/25585418/02a10250-59ea-40bb-8a80-9cd67344044b)
![image](https://github.com/leekelleher/umbraco-contentment/assets/25585418/5c7f9144-d649-4bef-99d1-1515805e31ca)

I've had this exact issue myself before and I fixed it in the URL Tracker here:
https://github.com/Infocaster/UrlTracker/blob/v13/develop/src/UrlTracker.Backoffice.UI/UrlTracker.Backoffice.UI.csproj#L20

You can see that the files are explicitly excluded between line 19 and 26

### Steps to reproduce

1. Install the package
2. Notice the additional files as references inside your project

### Expected result / actual result

I should not see the package.json file of contentment. It shouldn't be included in the nuget package. I see that it is included.

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

**Comment by D-Inventor** [comment]
Looking into the NuGet package with the package explorer, I can confirm that it is only package.json and package-lock.json:
![image](https://github.com/leekelleher/umbraco-contentment/assets/25585418/a298c456-8e8a-46f8-9e98-8373f0240901)

**Comment by leekelleher** [comment]
Doh! 🤦  Thank you for spotting this @D-Inventor and letting me know. 🙏  I'll tidy it up for a patch release.

**Comment by niekvanderreest** [comment]
Hi @leekelleher,

This issue is also including a reference to node_modules folder, currently it's causing my solution to get stuck building, i've reverted to v4.7 for the moment, just letting you know. contentment remains an awesome extension and i thank you for your work and commitment!

**Comment by leekelleher** [comment]
I've got around to patching this up in [Contentment v5.0.1](https://github.com/leekelleher/umbraco-contentment/releases/tag/5.0.1).
