### ISSUE TITLE
Data Picker: Error when property's `readonly` state is altered (in `SendingContentNotification`)

### ISSUE THREAD

**Issue by bielu** [leekelleher/umbraco-contentment#401]
### Which Contentment version are you using?

4.6.1

### Which Umbraco version are you using? For example: 13.2.1 - don't just write v13

13.3.0 (but will happen on all <14)

### Bug summary

If you have property which depends on SendingContentNotification where status of   property.Readonly is changed. it fails  to work correct with  n.model.value.push is not a function, because  n.model.value is empty string. ### 

### Steps to reproduce

1) add property which is DataPicker
2) create SendingContentNotification  handler, which modifies readonly status based on other property
3) change property value to ensured that status after publish changed from readonly to not readonly
4) try to add value

### Expected result / actual result

Property modal should be able to save value and close and keep new value.

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

### What browsers are you seeing the problem on?

Chrome, Edge

**Comment by leekelleher** [comment]
Hey @bielu, I've had a look at this, and can reproduce the issue. But there's something else going on with the save lifecycle, there doesn't appear to be a way for a property-editor's controller to re-initialize itself after the Save response re-populates the `$scope`, unless I'm missing something in AngularJS? 🤔 

The code suggestion you've made will be fine for Data Picker (although I'd say have it in both the `init()` and the `submit` callback). But I'm curious how other property-editors with non-`string` values handle the same scenario, e.g. Block List.

In terms of patching, I currently have a v5.0.1 lined up, but I see you've put v4.6.1 on this issue. Is v5 a viable upgrade for you? or would you need a v4.7.1 patch release? If so, that would take me a little more time... so would be after CodeGarden week.

**Comment by bielu** [comment]
@leekelleher I forked off and release internal version but v5 update will be great for new projects

**Comment by leekelleher** [comment]
I've added a patch for Data Picker in [Contentment v5.0.1](https://github.com/leekelleher/umbraco-contentment/releases/tag/5.0.1).
