### ISSUE TITLE
v14: Add weigth to dashboard

### ISSUE THREAD

**Issue by enkelmedia** [leekelleher/umbraco-contentment#403]
### Which Contentment version are you using?

v6.0.0-alpha001

### Which Umbraco version are you using? For example: 13.2.1 - don't just write v13

v14.0.0

### Bug summary

A simple one, just think that the dashboard should not be the first one in settings, especially with the big red "status update" box =D 

![image](https://github.com/leekelleher/umbraco-contentment/assets/1782524/3198db1e-fb6f-4cdb-805b-59211c1815ad)

### Steps to reproduce

Install, go to settings

### Expected result / actual result

Just change the weight of the dashboard when registering, or maybe use a custom workspace?

![image](https://github.com/leekelleher/umbraco-contentment/assets/1782524/018c92ff-e31d-42bb-a25b-91b8980892a6)

### Do you have Umbraco ModelsBuilder enabled?

- [ ] Yes, it is enabled.

**Comment by leekelleher** [comment]
@enkelmedia Thank you for the feedback. ❤️ 

I made the dashboard to be **deliberately annoying** (with the highest weighting - in both Content and Settings) during the alpha release(s), mostly to make note that it **is** an alpha release. It'll be removed once out of alpha, (as mentioned on the dashboard itself).

This is all in the hope that it may prevent anyone going into production with it. 😊

**Comment by enkelmedia** [comment]
I see 🙈🙈 It make sense! :)
