### ISSUE TITLE
Accessibility review

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#41]
In light of the great success of the [Umbraco Accessibility Team](https://our.umbraco.com/get-involved/the-accessibility-team/), I'd like for Contentment to pull it's own weight and ensure that the same principles have been applied.

I've tried to make efforts to ensure accessibility, e.g. use of `<button>`, ARIA, labelling, etc.  But I'm never sure it is truly accessible.  It'd be great to have help with accessibility concerns.  _I'd love to learn something too._

**Background reading**

- https://our.umbraco.com/forum/contributing-to-umbraco-cms/96398-call-for-an-accessibility-team
- https://github.com/umbraco/Umbraco-CMS/issues/5277
- https://trello.com/b/7M8RosrE/umbraco-accessiblity-issues-84

**Feedback, expectations and Hackotoberfest**

Whilst code patches are hugely appreciated, my expectation for collaboration on any accessibility review is more about raising issues for feedback. My hope is to highlight any accessibility issues that even seasoned developers can mistake.

**Pull Requests _(so far)_ ...**

- #45 ContentBlocksOverlay: Various changes (thx @BatJan)
- #44 ConfigurationEditorOverlay: Make use of Umbraco directives and change `<a>` to `<button>` (thx @BatJan)
- ba20147c0efffc1561c3e4d564904b955387c05c ItemPicker overlay - change `<a>` to `<button>` (me, @leekelleher)

**Comment by zersiax** [comment]
I do not currently have an Umbraco environment set up. If you can give me access to a demo site with this plugin added I'd be happy to take a look :-)

**Comment by leekelleher** [comment]
Hi @zersiax, thanks offering to help! I don't currently have a publicly accessible demo site.

I can try to put one together, but wouldn't be immediate, as currently have a client deadline looming.

In the meantime, if anyone else from the community would like to set a demo site up, that would be greatly appreciated. 🙏

**Comment by greystate** [comment]
@leekelleher @zersiax I can set one up w/ v1.1 and provide access, no problem

**Comment by leekelleher** [comment]
Awesome, thank you @greystate! 👏

**Comment by greystate** [comment]
No problem @leekelleher 

@zersiax Throw me an email at `chriztian[at]steinmeier.dk` and I'll invite you to the site.

**Comment by leekelleher** [comment]
Closing off this specific ticket, as it should be an ongoing concern.
I'll endeavour to review and improve the accessibility of the editors. 👍
