### ISSUE TITLE
Disabled attribute stopped working in the DataListItem enum decorator

### ISSUE THREAD

**Issue by ulrichebsen** [leekelleher/umbraco-contentment#411]
### Which Contentment version are you using?

5.0.1

### Which Umbraco version are you using? For example: 13.2.1 - don't just write v13

13.4.1

### Bug summary

Previously I have used the disabled attribute a lot as a workaround for setting a default value that is not shown for the editor ion cases where the datatype using the enum is not initialised. I then set it the disabled item as the first item, which will be returned in my views if the editor has not set a value (ie block grid settings), and in my code just set that value as the same as my default in cases where the default value is not the first value (ie a list of margins from none til full, where the default is somewhere in bewteen). Adding ths attribute now gives an error saying "Disbaled is not a valid named attribute argument because it is not a valid attribute parameter type"

I use the feature a LOT, so I hope that this is an easy fix.. ;) 

![image](https://github.com/user-attachments/assets/22966be9-c295-4ee4-974c-6cc18d5dd4d2)

### Steps to reproduce

![image](https://github.com/user-attachments/assets/0c677c5f-79f1-4c47-b5af-bcb7e6668866)

### Do you have Umbraco ModelsBuilder enabled?

- [X] Yes, it is enabled.

**Comment by leekelleher** [comment]
@ulrichebsen Thank you for reporting this! That's quite an oversight on my behalf. I've released a hot-fix, [Contentment 5.0.2](https://github.com/leekelleher/umbraco-contentment/releases/tag/5.0.2).
