### ISSUE TITLE
Data List: Add option to remove extension for file datasource

### ISSUE THREAD

**Issue by lars-erik** [leekelleher/umbraco-contentment#42]
Would be nice to be able to remove for instance .cshtml from views.  
Let me know if the request is unclear or you'd want a PR. 👼

**Comment by leekelleher** [comment]
@lars-erik Thanks for the suggestion, it's a good one. 👍 

I'm thinking it could either be done automatically, _(I'm wondering if the file extension is useful or not 🤔),_ or whether to add a config option to remove the file extension?

_Note to self: This is the line..._ https://github.com/leekelleher/umbraco-contentment/blob/1.0.1/src/Umbraco.Community.Contentment/DataEditors/DataList/DataSources/PhysicalFileSystemDataSource.cs#L66

**Comment by leekelleher** [comment]
@lars-erik I'm also wondering about spacing out PascalCase file names? (again, either as an option or default)
_What do you think?_ 🤔

**Comment by lars-erik** [comment]
I just made the views I pointed to _with_ spaces in the names. 😆  
Would be surprised if anyone would be gruntled about doing both the pascal splitting and extension removal.  
Maybe if it points to images and you can choose between .tif and .png. 🤷‍♂️

**Comment by leekelleher** [comment]
You've nerd sniped me! 😆  (aka lunch time hacking)

Here's my current thinking...

![Screenshot 2020-10-06 133138](https://user-images.githubusercontent.com/209066/95201853-6728f580-07d8-11eb-8789-f9eeb6cf119f.png)

**Comment by leekelleher** [comment]
@greystate 👀 I see you.  Wondering if there are any other (simple) string manipulations that people may want?
I was thinking lowercase/uppercase, but maybe feels overkill. 🤔

**Comment by lars-erik** [comment]
> @greystate 👀 I see you. Wondering if there are any other (simple) string manipulations that people may want?
> I was thinking lowercase/uppercase, but maybe feels overkill. 🤔

I can't answer this, because I get so nerdsniped that I'd suggest bringing [Superpower](https://github.com/datalust/superpower) into the picture. 😆 (It's already bundled with Umbraco...)

**Comment by greystate** [comment]
> Wondering if there are any other (simple) string manipulations that people may want?

Right off the 🦇 I can't come up with any — the ones listed should cover the scenario where you're actually picking a file, but by clever naming you can make an editor choose between **Column Layout** or **Grid Layout** by actually picking `columnLayout.css` or `gridLayout.css`, right? 

🤔 ... maybe the **Space out** option should cover both `columnLayout.css` and `column-layout.css` ?

**Comment by mattbrailsford** [comment]
<2cents>
I’d say go with less options and just be opinionated. Either have no options and just auto parse the files or maybe have one option of “Use friendly names” or something and this auto strips the file extension and splits pascal/camel/kebab case strings. 
</2cents>

**Comment by lars-erik** [comment]
> “Use friendly names”

"Be Matt Brailsford!"

**Comment by leekelleher** [comment]
@lars-erik I have no idea what **Superpower** does. Something to read up on later. 👍 

@greystate I hadn't considered dashes (kebab-case). 👍 

@mattbrailsford I had the same thought initially, (a single checkbox), then wanted to explore the idea a bit. Nothing set in stone. My preference is simpler options too. 👍

**Comment by lars-erik** [comment]
Never mind Superpower. It's a tool to build DSLs. Totally overkill. Would give the option of "scripting" the string manipulation.  
Reason it's in Umbraco is the serilog query language.

**Comment by leekelleher** [comment]
...and as if by magic, looky what I found in Core... [`.ToFriendlyName()`](https://github.com/umbraco/Umbraco-CMS/blob/release-8.8.0/src/Umbraco.Core/StringExtensions.cs#L1359) 😆

**Comment by leekelleher** [comment]
Done. Implemented in 8c3d64922f20e6ace1fe60cbc062f6b0ab0b01a9. It'll be part of the upcoming v1.1.0 release, _(which will be out once I've got around to writing the Content Blocks documentation)._

@lars-erik Thanks for the suggestion. Thanks @greystate and @mattbrailsford for feedback. 🎉

**Comment by lars-erik** [comment]
That might be the fastest implemented feature request I ever got. 😁👍 #h5yr
