### ISSUE TITLE
Skybrud.Redirects- Redirects section  not appearing live server after F5 rules applied

### ISSUE THREAD

**Issue by lbhanu** [leekelleher/umbraco-contentment#46]
**Note: for support questions, please use the [Umbraco Community forum](https://our.umbraco.com)**. This repository's issues are reserved for bug reports and feature requests.

### What is the current behavior?

Locally and stage environment Redirects section not appering, after we cleard the client dependency cache files then started t o work on local stage environment but not in live environment
Issue :DependencyHandler.axd?The controller with the name 'SkybrudUmbracoRedirects.Dashboard.Controller' is not registered.
https://errors.angularjs.org/1.7.5/$controller/ctrlreg?p0=SkybrudUmbracoRedirects.Dashboard.Controller

IF we click on add new redirect its showing the above  error in live environment .F5 rules are applied on the live server.

Please help us asap. We already pushed the files to live server and not working.

### Please tell us about your set-up:

- Contentment version: []
- Umbraco version: [8.5.5]
- Browser _(if applicable?)_: [all | Chrome XX | Firefox XX | Edge XX | Safari XX ]

**Comment by leekelleher** [comment]
Hi @lbhanu, I'm not sure what this has to do with the Contentment package. I'm closing this ticket.

But I'm happy to re-open it if you've found that the 2 packages somehow conflict with each other.

**Comment by lbhanu** [comment]
Hi leekelleher,

Sorry.This issues  is related to Skybrud.Redirects 2.0.4 version  package. not with the contentment package.

**Comment by leekelleher** [comment]
@lbhanu No problem. The repository for Skybrud.Redirects is here: <https://github.com/skybrud/Skybrud.Umbraco.Redirects>

One thing to try before you raise a ticket on that repository, try incrementing the `version` number in the `/Config/ClientDependency.config` file. 👍
