### ISSUE TITLE
Translations wanted! 🙏

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#47]
### Is your feature request related to a problem? Please describe.

I've been slowly moving out any hardcoded labels to the English localisation file.

<https://github.com/leekelleher/umbraco-contentment/blob/develop/src/Umbraco.Community.Contentment/Web/UI/App_Plugins/Contentment/lang/en.xml>

Of course, this is only good for English. Less good for others. It could be better.

### Describe the solution you'd like

If anyone is interested in supplying localisations/translations, that would be hugely appreciated.

---

**Translations _(so far)_ ...**

- #48 Danish (tak, @greystate)
- #50 Portuguese (Brazilian) (obrigado, @RenanOD)

**Comment by greystate** [comment]
I'd love to do the Danish translation.

We'll copy the `en.xml` to a `da.xml` and change in there, right?

**Comment by leekelleher** [comment]
@greystate Yes, 100%! Thank you.

**Comment by RenanOD** [comment]
Hi! I just included a BR portuguese translation :smile:

**Comment by leekelleher** [comment]
@RenanOD Awesome, thank you! _(I'll reply on the PR soon.)_

**Comment by leekelleher** [comment]
Closing off this specific ticket.

I'll make reference in the README (and Contribution guidelines) to that supplying localisations/translations is very much welcome! ❤️ 

Once again, thank you @greystate and @RenanOD for your contributions! 🙌
