### ISSUE TITLE
Comparing on name - not value?

### ISSUE THREAD

**Issue by soreng** [leekelleher/umbraco-contentment#52]
Hi,

I was using the data list to create a list of data (duuh), but I have some items that have the same name, but differs on description and value. I was trying to figure out why I could not pick the items that where named the same, and found this line:

https://github.com/leekelleher/umbraco-contentment/blob/86a39b23c1c1952cd90771b9d3b6e3ec02da9660/src/Umbraco.Community.Contentment/DataEditors/ItemPicker/item-picker.js#L83

If I allowDuplicates it will allow me to pick the same item multiple times, resulting in the same value returned multiple times when reading the property. It seems that the above line should have been:

`return _.find(vm.items, function (y) { return x.value === y.value; });`

**Comment by leekelleher** [comment]
@soreng Good spot!

I can't remember why I used `name` instead of `value`. I'm sure there was a reason. 🤔 I'll take a look tomorrow.

**Comment by soreng** [comment]
I tried to use the comparison on value, and it seemed to work in my case

Please let me know if I can help in any way :)

**Comment by leekelleher** [comment]
@soreng Updated the code and tested it out, working with my various demo data. The fix will be apart of upcoming v1.1 release. Thanks again for spotting and raising this bug. 🙏
