### ISSUE TITLE
Data List: Value Converter bug when ModelsBuilder is not enabled

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-contentment#56]
When ModelsBuilder is not enabled, Umbraco will use [`NoopPublishedModelFactory`](https://github.com/umbraco/Umbraco-CMS/blob/release-8.6.1/src/Umbraco.Core/Models/PublishedContent/NoopPublishedModelFactory.cs). The issue is that this factory will set the property's `CrlType` to be [`typeof(IPublishedElement)` via ` MapModelType()`](https://github.com/umbraco/Umbraco-CMS/blob/release-8.6.1/src/Umbraco.Core/Models/PublishedContent/NoopPublishedModelFactory.cs#L18).

This caused an issue in Data List's value-converter as I used the `propertyType.ClrType` to figure out if the target value should be `IEnumerable<T>` or not. <https://github.com/leekelleher/umbraco-contentment/blob/1.1.0/src/Umbraco.Community.Contentment/DataEditors/DataList/DataListValueConverter.cs#L126>

Of course, this wasn't compatible, so Data List's value-converter ended up returning the values as a comma-separated string.

### What is the current behaviour?

When using the Umbraco Content data source, and ModelsBuilder is disabled, the values (from `IPublishedContent`) is returned as a comma-separated `string`, instead of `IEnumerable<IPublishedContent>`.

### What is the expected behaviour?

I'd expect the value to be returned as `IEnumerable<IPublishedContent>`.

### Please tell us about your set-up:

- Contentment version: [1.1.0]
- Umbraco version: [8.6.1]

### Anything else?

Thanks to @marcemarc for helping to identify this bug.

**Comment by marcemarc** [comment]
When you @ me in on these self bug reports, it always sounds so serious and I always get the bit from Star Wars in my head:

https://www.youtube.com/watch?v=k_4_NNHRjb4

**Comment by leekelleher** [comment]
@marcemarc 🤗
I wasn't going to self-raise a bug report, but then realised I'd have nothing else to put in the patch release notes! 😆

**Comment by leekelleher** [comment]
Fixed in 103059cc2c449599f09e6d984ec0fc4ec5fb3e18
