### ISSUE TITLE
Umbraco 8 - Blocklist not working anymore after installing package

### ISSUE THREAD

**Issue by SRandomName** [leekelleher/umbraco-contentment#58]
### What is the current behaviour?
using Umbraco.Core.Models.Blocks; not found anymore after installing contentment package

### Please tell us about your set-up:

- Contentment version: [1.1.1]
- Umbraco version: [8.8.0]

![image](https://user-images.githubusercontent.com/48089189/102469664-50621300-4053-11eb-99b9-e11e1e429f35.png)

**Comment by leekelleher** [comment]
@SRandomName Thanks for raising this.  Do you have any more details, e.g. does anything looks suspect in the Umbraco error logs?

**Comment by SRandomName** [comment]
I have some more information about the project setup:
We have a web project where contenment is successfully installed.
We have a Code project for all custom code (Dll is copied on build to the web project).

Installing contenment in the code project is giving us this error.
We want to have contentment installed on the code project so we can create custom data list sources.

**Comment by leekelleher** [comment]
Hi @SRandomName, I've given this a quick test. I've set-up a clean Umbraco v8.8.0 install, configured a basic Block List editor (with a couple of Element Types), got that rendering on the frontend - all good.  Then installed the Contentment package (via the backoffice packages section installer), success, then tried the frontend - it rendered fine.

Meaning (to me) that Contentment and Block List do play fine together.

---

What I suspect has happened for you - _and this is purely an educated guess_ - is that (somehow) when you've added Contentment to your code project (via NuGet, I assume?), the Umbraco dependency got set to v8.6.1 (which is the minimum Umbraco version that Contentment works with)... and then (again somehow) when you compile/build your code project, the v8.6.1 assemblies have been copied over to your web project ... which, of course, is v8.8.0, but now with v8.6.1 DLLs.

I can't say for sure how the code project got in that state, but I think the resolution would be to ensure that your code project has updated NuGet references to Umbraco v8.8.0.

Like I say, that's mostly guesswork on my behalf.

**Comment by SRandomName** [comment]
Indeed, UmbracoCms.Core & UmbracoCms.Web are both set to v8.6.1. Going to update both back to v8.8.0 and i'll let you know if this fixes the problem.

**Comment by SRandomName** [comment]
@leekelleher : This fixed the problem. Thank you !

**Comment by leekelleher** [comment]
@SRandomName Glad to hear it's resolved. 👍
