### ISSUE TITLE
Enum data source - set a default value

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#60]
### Is your feature request related to a problem? Please describe.

The Data List configuration using .NET Enumeration works great for e.g. Text Size and Text Position in settings of a Block List editor block. However by default in use the first enum value as default value even though no value has been selected in the list editor.

### Describe the solution you'd like

It would be great if we could configurate e.g Checkbox List, Dropdown List or Radio Button List selecting one or more default options.

**Comment by leekelleher** [comment]
Hi @bjarnef, thanks for raising this.

According to the Microsoft docs, the default value of an Enum is `0`...

> The default value of an enumeration type `E` is the value produced by expression `(E)0`, even if zero doesn't have the corresponding enum member. <https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum>

This means that it will either use whichever enum member is set to `0`, or the first one. So it'll always have a default value.

If you have control over the Enum, then a workaround would be to set whichever you'd like the default to have a value of `0`.

---

I have thought about ways to set a default value, but it started to get complex with the disconnect between the data source and list editor.  Needs more thought and prototyping. 😃

**Comment by bjarnef** [comment]
@leekelleher yeah, I know. However I think in some cases if might make sense to have a default option in the UI, while keeping the default enum values - especially if using the enum in configuration of multiple data type instances.

E.g. a WeekDay or .NET `DayOfWeek` enum. You might use the default values to make it easier to work with `Calendar` and `DateTime` objects in .NET, but for some reason the client might prefer Friday to be selected as default in Radiobutton List.
https://docs.microsoft.com/en-us/dotnet/api/system.dayofweek?view=net-5.0

Furthermore if used in Checkbox List it would be might be useful to make Monday - Friday selected by default, while Saturday and Sunday are unselected.

**Comment by leekelleher** [comment]
@bjarnef, thank you - I do like the idea of setting a default value, _(whether this is for Enum data source or any other),_ but I struggle with where (conceptually) the user would configure that?

e.g. is it the responsibility of the data source? or the list editor? _(but then I'd designed the list editor to be agnostic of data source)_

I could argue that this could be done using Content Templates (blueprints), but then BlockList/NestedContent doesn't support those, (although [Contentment's Content Blocks](https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/editors/content-blocks.md) does).

Or a last resort (as a developer), programmatically set a default value using a [`EditorModelEventManager.SendingContentModel` hook](https://our.umbraco.com/documentation/reference/events/EditorModel-Events/#usage)?

I guess this comes down to whether we need a solution for a specific problem, or it's a more conceptual question, _should Data List be able to define a default value?_

Hopefully, I'm not sounding like I'm trying to shut down any discussions... I'm totally happy to hear any proposed ideas. 🙏

**Comment by bjarnef** [comment]
@leekelleher I imagine this is something to configurate in the list editor (or maybe overwrite the value from data source).

With a enum data source and a checkbox list, I guess it isn't possible to set multiple default checked values?

In a specific use-case I am using enum data source + radiobutton list for some block lidt configuration settings.

*Text Position*
Left, Center, Right
In this case when no value is selected "Left" is default, which is fine in this case.

*Text Width*
Small, Medium, Large
In this case when no value is selected "Small" is default, but actually I would like to have "Large" as default as it represent full width :)

**Comment by Matthew-Wise** [comment]
Ran into this issue today as well, when using drop down list in my case the first option been default was fine however the dropdown was not pre populated so I had to add some code using `EditorModelEventManager.SendingContentModel`.

I think the control of default value should sit with the editor, this would allow the data source to be reused with different default values based on its use case. This would also allow the checkbox list to have multiple selected, as its in control.

**Comment by leekelleher** [comment]
I'm not convinced that the List Editor is the appropriate place to configure a default value - since it knows nothing about the data source, (and making it aware of the data source would introduce much complexity).

Potential idea could be to make use of the proposed Preview panel, see PR #53. Which would display a rendering of the configured Data List editor.

![Data List Preview idea](https://user-images.githubusercontent.com/209066/99831422-f014aa00-2b56-11eb-9bf3-0b3c9b3d0726.png)

But I'm not 100% on this, conceptually in Umbraco we do not (generally) define default values at Data Type level - which is why Content Templates exist. (I'm aware this isn't ideal for sub-content editors, a la BlockList, NC, DTGE, et al) 🤔

**Comment by Matthew-Wise** [comment]
I can see you're point about defaults and content templates.

Maybe it's more of a documentation task to highlight setting a default value using code? (by linking out to our or a more complex example)

Not sure if you could set a default value by data type definition easily using  `EditorModelEventManager.SendingContentModel` though, it would have to be by document type / property definition.

**Comment by leekelleher** [comment]
Quick thought about an default value for the Enum specifically... I wonder if the object-type should be Nullable Enum instead? 🤔

**Comment by Matthew-Wise** [comment]
> Quick thought about an default value for the Enum specifically... I wonder if the object-type should be Nullable Enum instead? 🤔

If allow empty or generally?

**Comment by leekelleher** [comment]
General, (as the Data Source knows nothing about the List Editor's config).  It could be configurable at the Enum Data Source level... but then I start to feel it's death by config options, which is what I nearly fell into with issue #42 (many granular options vs. a single sensible one)
