### ISSUE TITLE
Use custom views for list editors

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#69]
### Is your feature request related to a problem?

I wonder if we could enhance the editor experience with custom views a bit similar to Block List editor custom views, but also the cool thing NuPickers offered using macro partial views.
https://our.umbraco.com/packages/backoffice-extensions/nupickers/

### Describe the solution you'd like

I would be great if we for example in dropdown list or radiobutton list could use a custom view, where we have the data from the source available.

![image](https://user-images.githubusercontent.com/2919859/109789120-4c846c80-7c10-11eb-8583-f88ed383670b.png)

E.g. the render the single/multi choice as `labels/buttons` like in this screenshot from Umbraco Uno, or present some color options with some visual colors like in the screenshots for NuPickers package.

![image](https://user-images.githubusercontent.com/2919859/109788689-d5e76f00-7c0f-11eb-8669-226e1fbc4869.png)

Or maybe just want to show some icons based on the values, e.g. alignment: Left, Center, Right

**Comment by leekelleher** [comment]
The upcoming [v1.2 release](https://github.com/leekelleher/umbraco-contentment/blob/develop/.github/ROADMAP.md#v12) will have a list-editor called **Templated List** - which you can use custom AngularJS markup to render items.

I'd looked at using Macros, but it felt quite heavy - making a HTTP request per item.

Failing that, there is the ability to [make your own custom list editor](https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/editors/data-list.md#extending-with-your-own-custom-list-editor).

**Comment by bjarnef** [comment]
@leekelleher yeah, the macro partial view in NuPickers was a bit slower to render the custom view and these days I think it would be fine using AngularJS views 👍
