### ISSUE TITLE
Dropdownlist shows empty option even when not allowed in config when creating new content

### ISSUE THREAD

**Issue by dawoe** [leekelleher/umbraco-contentment#81]
### What is the current behaviour?

I created a datatype with the following configuration.

![image](https://user-images.githubusercontent.com/1193822/112159928-f2147580-8be9-11eb-8718-65ffdeb08b66.png)

When I created content of a document type with this datatype I still see a empty option

![image](https://user-images.githubusercontent.com/1193822/112160070-1a9c6f80-8bea-11eb-9fbb-5159d952ab13.png)

I outputted the value of vm.allowEmpty for testing purposes.

### What is the expected behaviour?

I would like to see no empty option. Now I have to make the property mandatory to make sure a article type is set.

### What is the motivation / use case for changing the behaviour?

I think this get's added because $scope.model.value is a empty string in this case.

Maybe it would be a good option to set $scope.model.value to the first item in the list when allowEmpty is false and no value has been set yet

### Please tell us about your set-up:

- Contentment version: [1.2.0]
- Umbraco version: [8.7.3]
- Umbraco ModelsBuilder enabled
- 
- Browser _(if applicable?)_: [all | Chrome XX | Firefox XX | Edge XX | Safari XX ]

**Comment by leekelleher** [comment]
Yeah, it's a limitation of AngularJS `ng-options`. As far as I could find there wasn't a way to remove it, (when the initial value is unset).

I'll have a think about setting the default value to the first option, I'm unsure whether it's considered presumptuous or not. 🤔

_(I've had discussion on other issues about default values for things like Enums, where some folk say that's undesired ... Content Templates are my usual response for setting default values for Content properties)._

**Comment by dawoe** [comment]
Hi Lee,

I have created a PR for this. Feel free to merge or not.

But considering there is a option not to have empty values, this should be the case. Also when creating new content. When editing existing content that has a value set there is no empty option available.

Dave

**Comment by dawoe** [comment]
LOL... I just see I targeted the PR at my own fork. Will fix that

**Comment by leekelleher** [comment]
After thinking about, I'm happy with this approach. 👍
Although it does make me question the same for radio-button lists, e.g. should they have an empty value? 🤔 

Closing this ticket, fixed in pull request #82.
