### ISSUE TITLE
Compiler warning when using Umbraco's ComposeAfter attribute

### ISSUE THREAD

**Issue by tompipe** [leekelleher/umbraco-contentment#84]
### What is the current behaviour?
Not possible to use Umbraco's `ComposeAfter` attribute to ensure an `IUserComposer` runs after `ContentmentComposer` e.g

`[ComposeAfter(typeof (Umbraco.Community.Contentment.Composing.ContentmentComposer))]`

Generates a Compiler Error CS0122 due to `ContentmentComposer` marked as internal

### What is the expected behaviour?

No compiler warning when using `[ComposeAfter(typeof (Umbraco.Community.Contentment.Composing.ContentmentComposer))]`

**Comment by tompipe** [comment]
Fixed in #83

**Comment by leekelleher** [comment]
Closing off this ticket, as discussion can be done on PR #83.

I don't consider it a bug, as the class was intentionally marked as `internal`.
