### ISSUE TITLE
Add example of data source using dependency injection

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#94]
I found this example useful:
https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/editors/data-list.md#extending-with-your-own-custom-data-source

In my use-use I have an service to fetch some external data.
I was wondering if I could inject the service, so I tried that and it seems to work 😎 

It could be useful to mention that in the docs:

```
public class BrandGroupsDataSource : IDataListSource, IDataListSourceValueConverter
{
    private readonly IBrandService _brandService;

    public BrandGroupsDataSource(IBrandService brandService)
    {
        _brandService = brandService;
    }

    public string Name => "Brand groups";

    public string Description => "Data source for all the brand groups.";

    public string Icon => "icon-brick";

    public OverlaySize OverlaySize => OverlaySize.Small;

    public Dictionary<string, object> DefaultValues => default;

    public IEnumerable<ConfigurationField> Fields => default;

    public IEnumerable<DataListItem> GetItems(Dictionary<string, object> config)
    {
        var items = new List<DataListItem>();
        var groups = _brandService.GetGroups(new int[] { });

        foreach (var group in groups)
        {
            items.Add(new DataListItem
            {
                Description = group.Description,
                Name = group.Name,
                Value = group.Id.ToString()
            });
        }

        return items;
    }

    public Type GetValueType(Dictionary<string, object> config)
    {
        return typeof(BrandGroup);
    }

    public object ConvertValue(Type type, string value)
    {
        return null; // TimeZoneInfo.FindSystemTimeZoneById(value);
    }
}
```

I guess that `ConvertValue()` method also need a method to fetch the item by the stored value.

**Comment by bjarnef** [comment]
Furthermore I guess this would need to adjusted to single/multi picker? Currently this only returns a single object although the picker is configurated as multi picker.

```
public Type GetValueType(Dictionary<string, object> config)
{
       return typeof(BrandGroup);
}
```

It seems the `ConvertValue` method is used when accessing the list property on e.g. a Brand Page `@(Model.Groups)` which seem to load a bit longer compared with Brand Page without this picker.

```
public object ConvertValue(Type type, string value)
{
      var groups = _brandService.GetGroups(new int[] { });
      return groups.FirstOrDefault(x => x.Id.ToString() == value);
}
```

**Comment by leekelleher** [comment]
@bjarnef Thanks for the suggestion of adding dependency injection reference to the documentation, good idea! 👍 

---

With the `GetValueType` and `ConvertValue` method, it's correct that they only deal with single values. It's the [`IDataListEditor.HasMultipleValues`](https://github.com/leekelleher/umbraco-contentment/blob/master/src/Umbraco.Community.Contentment/DataEditors/DataList/IDataListEditor.cs#L14) that deals with the multiple/single aspects.

I can appreciate that it may seem less performant, especially if an API, e.g. say Umbraco's Content cache API, where there are more optimum calls to query and return multiple values.  But that's my compromise of Data List's design, (separating the data-source from the list-editor).

Of course, I don't know what `_brandService.GetGroups` is doing under the hood - it could be querying a database in a different country 🤷 - but could that be cached/optimised? could it have additional methods? `_brandService.Get(value)`?

I'm trying to recall if ModelsBuilder _(or could be Umbraco's PropertyValueConverter logic)_ handles it's own caching strategy, so might be the first _hit_ that's the most expensive? 🤔

**Comment by bjarnef** [comment]
It seems the `ConvertValue()` is per item, so in this case it would make a request per item.
Using a multi picker where an array of id values are stored, isn't it possible to convert all values once?
Often it is possible to fetch entries by multiple ids from an external data source.

Alternatively I could store the value as JSON instead:

```
public IEnumerable<DataListItem> GetItems(Dictionary<string, object> config)
{
    var items = new List<DataListItem>();
    var groups = _brandService.GetGroups(new int[] { });

    foreach (var group in groups)
    {
        items.Add(new DataListItem
        {
            Description = group.Description,
            Name = group.Name,
            Value = JsonConvert.SerializeObject(group)
        });
    }

    return items;
}

public object ConvertValue(Type type, string value)
{
      if (string.isNullOrEmpty(value)) return null;

      return JsonConvert.DeserializeObject(value);
}
```

**Comment by bjarnef** [comment]
@leekelleher I have tried stored the data as JSON instead as I only have a few properties:

```
public IEnumerable<DataListItem> GetItems(Dictionary<string, object> config)
{
    var items = new List<DataListItem>();
    var groups = _brandService.GetAllGroups();

    foreach (var group in groups)
    {
        items.Add(new DataListItem
        {
            Description = group.Description,
            Name = group.Name,
            Value = JsonConvert.SerializeObject(group)
        });
    }

    return items;
}

public Type GetValueType(Dictionary<string, object> config)
{
    return typeof(BrandGroup);
}

public object ConvertValue(Type type, string value)
{
    if (string.IsNullOrEmpty(value))
        return null;

    if (value.DetectIsJson() == false)
        return null;

    return JsonConvert.DeserializeObject(value);
}
```

`@Models.Groups` in view is a collection, but it doesn't seem to contains items.

**Comment by bjarnef** [comment]
Okay with this 

```
```

**Comment by bjarnef** [comment]
@leekelleher it `ConvertValue()` I get the correct json in `value` for an item and also the correct deserlized object, but no items in view, e.g. `@(Model.Groups?.Count() ?? 0)`.

Am I missing something?

**Comment by leekelleher** [comment]
I'm trying to dissect what you're asking me. 😃 

> Using a multi picker where an array of id values are stored, isn't it possible to convert all values once?

No, not with Data List editor's current design.  With the separation between data-source and list-editor, the logic for deciding whether the output is a multiple or single is done by the list-editor. The data-source isn't aware of the list-editor's configuration. Hence the compromise for it only converting single values.

With serializing JSON, I'm not sure what to suggest, (as in I haven't tried that scenario myself).

With the `GetValueType` code snippet. The data-source is expecting the object-type of a single item/value, e.g. 

```csharp
public Type GetValueType(Dictionary<string, object> config) =>typeof(BrandGroup);
```

Ultimately whatever Type is being returned from `ConvertValue` should match the object-type from `GetValueType`.

**Comment by bjarnef** [comment]
Yeah, that's what I tried using `typeof(BrandGroup)`.
However when generating ModelsBuilder models the property will then be of type `BrandGroup` and not a collection although its a multi picker.

Changing to `typeof(IEnumerable<BrandGroup>)` and re-generate models then the property will be `IEnumerable<BrandGroup>` in `Model.Groups, but without any items.

**Comment by leekelleher** [comment]
@bjarnef I'm thinking that there's something up with the configuration of the Item Picker, as in, that's telling ModelsBuilder that the value is single, not multiple. Could "Maximum items" be set to 1?

Here's the logic for it... <https://github.com/leekelleher/umbraco-contentment/blob/develop/src/Umbraco.Community.Contentment/DataEditors/ItemPicker/ItemPickerDataListEditor.cs#L108>

**Comment by bjarnef** [comment]
With `typeof(IEnumerable<BrandGroup>)` I get `IEnumerable<BrandGroup>` in `Model.Groups`, but if I use:

`@(Model.Value<string>("groups"))` it returns `MyProject.Core.Models.BrandGroup`

really strange :)

And `@(Model.Value<MyProject.Core.Models.BrandGroup>("groups")` works to get a single item. But using `IEnumerable` or `List` doesn't seem to work. 

Really strange :)

Maximum items in item picker configuration is just empty.

![image](https://user-images.githubusercontent.com/2919859/115390944-2a09db00-a1df-11eb-85d2-e6366703034a.png)

**Comment by bjarnef** [comment]
Wait a moment, when I set Maximum items to zero and re-generate models I now get `IEnumerable<IEnumerable<BrandGroup>>` 😅

**Comment by bjarnef** [comment]
With maximum items set to zero and changing back to this seem to work 👍 

```
public Type GetValueType(Dictionary<string, object> config)
{
     return typeof(BrandGroup);
}
```

```
@{ 
    if (Model.Groups?.Any() == true)
    {
        <ul>
            @foreach (var group in Model.Groups)
            {
                <li>@(group.Id + " - " + group.Name)</li>
            }
        </ul>
    }
}
```

**Comment by leekelleher** [comment]
Something strange is definitely going on with the "Maximum items" field, (e.g. Contentment's NumberInput editor) with it emptying out "0" zero values.  If you re-configure your ItemPicker, the value will be empty. Very odd.

I'm investigating it, seems like a bug.

**Comment by bjarnef** [comment]
Yeah, when I re-open the configuration the value of "Maximum items" is empty.

![image](https://user-images.githubusercontent.com/2919859/115392483-e9ab5c80-a1e0-11eb-8c74-9978d9d15692.png)

**Comment by leekelleher** [comment]
It's definitely a bug. This line in NumberInput, <https://github.com/leekelleher/umbraco-contentment/blob/1.4.0/src/Umbraco.Community.Contentment/DataEditors/NumberInput/number-input.js#L27>, does a falsey check on whether to fallback to the default value (which is null)... and `0` is a falsey value in JavaScript, so defaults to `null`. Gah! 😖 

Expect a v1.4.1 patch release soon. 😆 

In the meantime, the workaround fix is to set the value for Maximum Items, close the panel, save the DataType, re-generate models.  Then if you need to edit the ItemPicker again, remember to manually set the max items again! 🤦

**Comment by bjarnef** [comment]
Cool, thanks @leekelleher much appreciated 😎 👍 
Yeah, I noticed that 😁

**Comment by leekelleher** [comment]
v1.4.1 is released. 👍 
+ updated the docs with info about Dependency Injection.  I don't give a full explicit in the docs, but link to an example within Contentment's source code.

**Comment by bjarnef** [comment]
Thanks @leekelleher 

I wonder if you have an example reading the property value from ContentService?

```
```

//var groups = entity.GetValue<List<IvensaGroup>>(ContentModels.BrandPage.GetModelPropertyType(x => x.Groups).Alias);
                        var rawJson = entity.GetValue<string>(ContentModels.BrandPage.GetModelPropertyType(x => x.Groups).Alias);
                        var groups = JsonConvert.DeserializeObject<List<IvensaGroup>>(rawJson);

**Comment by bjarnef** [comment]
@leekelleher I think the issue is that I have this:

```
public IEnumerable<DataListItem> GetItems(Dictionary<string, object> config)
{
    var items = new List<DataListItem>();
    var groups = _brandService.GetAllGroups();

    foreach (var group in groups)
    {
        items.Add(new DataListItem
        {
            Description = group.Description,
            Name = group.Name,
            Value = JsonConvert.SerializeObject(group)
        });
    }

    return items;
}
```

I guess Contentment serialize the `DataListItem` so it end up with double serialization.
Is there a reason `Value` is a `string` and not allow to be an `object`?

**Comment by bjarnef** [comment]
Not pretty by a workaround was this:

```
var rawJson = entity.GetValue<string>(ContentModels.BrandPage.GetModelPropertyType(x => x.Groups).Alias);

rawJson = rawJson.TrimStart('\"');
rawJson = rawJson.TrimEnd('\"');
rawJson = rawJson.Replace("\\", "");
rawJson = rawJson.Replace("\"{", "{");
rawJson = rawJson.Replace("}\"", "}");

var obj = JsonConvert.DeserializeObject<List<BrandGroup>>(rawJson);
```

**Comment by leekelleher** [comment]
@bjarnef _eek!_ 😬  Feels like you've been coded into a corner.

I'm not keen on the approach of serializing JSON for data-list item values. My intended design for Data List was meant to be for simple values... which is why the `DataListItem.Value` is a `string`. (The complexity of dealing with an `object` for the various list-editors would become a headache.)

If we take a step back to one of your original questions about `ConvertValue` accepting multiple values. If I was tackling it, I'd try using some sort of caching mechanism to speed it up.

e.g. sort the service's call in a local dictionary, and use that to populate/look-up the values.

```csharp
public class BrandGroupsDataSource : IDataListSource, IDataListSourceValueConverter
{
    private readonly Dictionary<string, BrandGroup> _lookup;

    public BrandGroupsDataSource(IBrandService brandService)
    {
        _lookup = brandService
            .GetGroups(Array.Empty<int>())
            .ToDictionary(x => x.Id.ToString());
    }

    // <snipped /> Name, Description, Icon, etc.

    public IEnumerable<DataListItem> GetItems(Dictionary<string, object> config)
    {
        _lookup
            .OrderBy(x => x.Value.Name)
            .Select(x => new DataListItem
            {
                Name = x.Value.Name,
                Value = x.Key,
                Description = x.Value.Description,
            });
    }

    public Type GetValueType(Dictionary<string, object> config) => typeof(BrandGroup);

    public object ConvertValue(Type type, string value) => _lookup.ContainsKey(value) == true ? _lookup[value] : null;
}
```

I'm not sure how that helps with the `ContentService` question you ask.  I'm unsure where that's happening, or it's purpose - none of my business really.

Your question about Contentment serializing the value - yes, but really it's Umbraco serializing it. The double-serialization happens when a serialized object contains other serialized objects. It is frustrating, but it's happening within Umbraco's datasource logic.

Not sure if I missed any of your other questions? Let me know.

**Comment by bjarnef** [comment]
@leekelleher yeah, you probably didn't design it to store JSON.

I found it could be simplified to the following though:

```
var rawJson = entity.GetValue<string>(ContentModels.BrandPage.GetModelPropertyType(x => x.Groups).Alias);

if (!string.IsNullOrEmpty(rawJson))
{
    rawJson = Regex.Unescape(rawJson);
    rawJson = rawJson.Replace("\"{", "{");
    rawJson = rawJson.Replace("}\"", "}");

    groups = JsonConvert.DeserializeObject<List<BrandGroup>>(rawJson);
}
```

Not sure how well the local caching would work, but maybe a simple JSON would be an option? E.g. 

```
public DataListValue
{
     public string Id { get; set; }
     public string Value { get; set; }
}
```

Sometimes you don't really need more than an Id/Reference and a name/value. Maybe an additional `Dictionary<string, string>` if a few more properties are needed?

**Comment by bjarnef** [comment]
@leekelleher I went with your suggestion which works well. It might be worth consider simple json for future development though :)

For this specific project I could use a multiple member picker to store some member references. Unfortunately Umbraco currently doesn't support this. I have submitted a PR here: https://github.com/umbraco/Umbraco-CMS/pull/7634

But I wonder if I easily can add this using Contentment with a similar approach.

**Comment by bjarnef** [comment]
@leekelleher just a few questions regarding the `_lookup` dictionary. Do you know for how long this is cached and could it be configurated?

**Comment by leekelleher** [comment]
In these examples, the `_lookup` Dictionary is per instance, remaining for a long as that object does. For these data-source, that's for the entire lifespan of the application.

How to invalidate the cache, that's the age old problem in computing!

Replacing with Umbraco's AppCache could help? Found this doco, but appears to be for v7. <https://our.umbraco.com/documentation/reference/cache/updating-cache>

**Comment by bjarnef** [comment]
Yeah, I noticed recycling the IIS would update the results. I also thought about using the cache mechanism in Umbraco as in the documentation you mention.
For Umbraco v8 I think it is now `AppCaches` which can be injected, but haven't worked with that yet in v8 project 😄
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Cache/AppCaches.cs

**Comment by bjarnef** [comment]
@leekelleher regarding a custom data source, it is possible to access current Umbraco node, e.g. another property on page and use this to filter / get the results in `_lookup`?

Currently it get all results, but could we access another property "Location" on content node and use the a "location id" to filter the results further?
