### ISSUE TITLE
Selecting multiple items in item picker only submit a single item

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#95]
### What is the current behaviour?

I have added a custom data source based on this example:
https://github.com/leekelleher/umbraco-contentment/blob/develop/docs/editors/data-list.md#extending-with-your-own-custom-data-source

Furthermore the datatype is configurated to use this data source and list picker.
However when selecting multiple items from overlay and hit submit it only submit a single item.
I can add multiple items clicking "Add" again, but I need need to do this per item.

### What is the expected behaviour?

To be able to select multiple items from item picker overlay.

### Please tell us about your set-up:

- Contentment version: [1.4.0]
- Umbraco version: [8.12.2]
- Umbraco ModelsBuilder enabled (AppData)
- Browser: all

**Comment by leekelleher** [comment]
@bjarnef I'm unable to reproduce this bug.

With the **Multiple selection?** option enabled, I am able to select multiple items in the panel, press the Select button and they are all added to the list.

I've tried with some other custom data-sources, but all working as expected.

Do you have any JS errors in the console? _(just wondering if there's an issue with an item's value)_

**Comment by bjarnef** [comment]
@leekelleher yeah, it seems to work again now. I guess it was an issue, when I switched from using `Id` as value to store and `JSON` object in value instead: https://github.com/leekelleher/umbraco-contentment/issues/94
