### ISSUE TITLE
Show existing selected items in item picker overlay

### ISSUE THREAD

**Issue by bjarnef** [leekelleher/umbraco-contentment#96]
### Is your feature request related to a problem? Please describe.

Currently based on Contentment v1.4.0 it seems the item picker has filtered/excluded existing selected items and only new non-selected items are listed in overlay.

### Describe the solution you'd like

It would be great it is was possible via configuration to show already selected items in item picker overlay, but disabled/dimmed. I think it depends on the use-case - sometimes you may want to see all items (but existing ones disabled, while it for other use-cases is great just to exclude existing selected items.

**Comment by leekelleher** [comment]
@bjarnef Thanks for the suggestion.

I'd thought about it originally, but in early prototypes it didn't feel quite right, the flow didn't work (for me).  I've chatted about it with various community people, and general conclusion is that the picker panel should show you want can be selected, not what you've already selected.  (Usually followed by conversations about UX psychology about reducing cognitive load, etc).

I did explore adding extra configuration for it, but again, felt too complicated.

I'll close off this ticket, as it's not something I want to invest time in exploring (again). _(Thanks again for the suggestion, I appreciate it.)_
