### ISSUE TITLE
Clear selection feature for Data List editors

### ISSUE THREAD

**Issue by torerikk** [leekelleher/umbraco-contentment#97]
In order for value fallback to work the value of a field must be cleared. As of version 1.4 this is not possible (at least to my knowledge) for the Buttons and Templated List editors.  

My request is that those two would work the same way that Dropdown List and Radio List does.
If you provide a Json data source like the following:

    [
        { 
            "name": "Inherit",
            "alias": ""
        },
        {
            "name": "Foo",
            "alias": "Bar"
        }
    ]

Using dropdown list (regardless of the "Allow empty" setting) or the radio list selecting "Inherit" will allow fallback to happen.
But for buttons or the templated list `Value(..)` will just return an empty string.

**Comment by torerikk** [comment]
After exploring more of the new features in 1.4 (like the Image Crops datasource) the Radio button list also could use some way of clearing the current selection with sources where adding an item with empty alias is not an option. I am however uncertain on how this would best be implemented. Both an optional "Not set" item and a "Clear selection" button comes to mind, but neither seems like the perfect option.

**Comment by leekelleher** [comment]
@torerikk Thank you for the suggestion.

My initial thought is that it could be a Property Action, re: <https://our.umbraco.com/documentation/extending/property-editors/Property-Actions/>

**Comment by leekelleher** [comment]
@torerikk Something like this?

![Screenshot 2021-04-20 162121](https://user-images.githubusercontent.com/209066/115422100-7c092b80-a1f4-11eb-9d62-ecca5bc97d67.png)

I'm not sure how "Not set" would be different to "Clear selection"? In my mind they'd do the same thing.

I'd have this as an opt-in configuration, as there are scenarios where you wouldn't want the selection cleared. (I have several internally within Contentment itself).

**Comment by torerikk** [comment]
I think that it would work great as an opt-in property action. Thank you :)

**Comment by leekelleher** [comment]
Cool. It'll be part of the v1.4.1 patch release... _should be out soon._

**Comment by leekelleher** [comment]
...and v1.4.1 has been released. 👍
